//! Pending operator-approval requests (S6b). When a mutating action Pauses
//! (`RequiresApproval` with no valid approval), the Hub persists everything the
//! OFFLINE operator needs to sign an approval for THAT exact action — and nothing the
//! Hub could use to mint one itself.
//!
//! A persisted row carries the `approval_id` (the single-use NONCE the operator signs
//! over), the `action_digest` (which transitively binds principal / scope / params /
//! derived-risk), the `expires_at` the approval will carry, the issuer, plus context for
//! the operator's decision (action verb, principal, scope, surface, run). The operator
//! (S6c CLI) reads this, signs `friday_core::gate::canonical_approval_signature_bytes`
//! for it with their Ed25519 private key, and the resulting approval is later ingested
//! and verified by [`crate::authorize_mutating_action_ed25519`] (the live resume
//! entrypoint is S6d).
//!
//! Truth label: this is the persistence MECHANISM + its tests only. It is NOT wired into
//! the live loop's Pause path (S6d). The `approval_id` nonce MUST be generated by the
//! caller from a CSPRNG (S6d's responsibility); this layer only stores what it is given,
//! and the `approval_id` PRIMARY KEY makes a duplicate nonce a fail-closed insert error.

use crate::error::Result;
use friday_core::gate::{self, MutatingActionRequest, CANONICAL_GATE_ISSUER};
use rusqlite::{params, Connection, OptionalExtension};

/// A persisted pending approval request — the offline operator's to-sign work item.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct PendingApprovalRequest {
    /// The single-use NONCE the operator signs over (also the eventual
    /// `CanonicalApproval.approval_id`). PRIMARY KEY — a duplicate nonce is refused.
    pub approval_id: String,
    /// The agent run that Paused waiting on this approval (so S6d can resume it).
    pub run_id: String,
    /// The action verb (operator-facing context).
    pub action: String,
    /// Hex SHA-256 of the request's `canonical_action_bytes` — binds the EXACT action
    /// (and transitively the principal / scope / params / derived-risk).
    pub action_digest: String,
    /// The requesting principal (operator-facing context; also bound INTO the digest).
    pub principal_id: Option<String>,
    /// The surface the action was requested on (operator-facing context).
    pub surface: String,
    /// Scope: the targeted resource type, if any (operator-facing context; also bound
    /// into the digest).
    pub resource_type: Option<String>,
    /// Scope: the targeted resource id, if any.
    pub resource_id: Option<String>,
    /// The expiry the eventual approval will carry (operator signs over this).
    pub expires_at: i64,
    /// Must be `friday_canonical_gate` (the value the approval will carry).
    pub issuer: String,
    /// Lifecycle status (`pending` until S6d ingests an approval; never auto-resolved
    /// here).
    pub status: String,
    pub created_at: i64,
    /// S6d: the raw tool-call key/value pairs (JSON `[[k,v],...]`) the run Paused on, so
    /// the resume entrypoint can re-execute the EXACT approved mutation. `None` for a
    /// pre-S6d row (the column is a nullable additive ALTER). The `action_digest` already
    /// binds these params transitively — the resume path recomputes the digest from the
    /// reconstructed call and cross-checks it, so a tampered `tool_params` cannot make a
    /// DIFFERENT mutation match the operator's signed approval. Hub-side only (never the
    /// wire).
    pub tool_params: Option<String>,
}

impl PendingApprovalRequest {
    /// Build a pending request bound to `request`'s EXACT action: the `action_digest` is
    /// computed here (not caller-supplied) from the same `canonical_action_bytes` the
    /// authorize path digests, so the persisted digest is guaranteed to match what an
    /// approval must bind. `approval_id` is the caller-generated single-use nonce (S6d
    /// supplies a CSPRNG value); `expires_at` is the expiry the approval will carry.
    pub fn for_request(
        request: &MutatingActionRequest,
        approval_id: &str,
        run_id: &str,
        expires_at: i64,
        created_at: i64,
    ) -> Self {
        let action_digest = friday_crypto::action_digest(&gate::canonical_action_bytes(request));
        let (resource_type, resource_id) = match request.resource() {
            Some(r) => (Some(r.resource_type.clone()), r.id.clone()),
            None => (None, None),
        };
        PendingApprovalRequest {
            approval_id: approval_id.to_string(),
            run_id: run_id.to_string(),
            action: request.action.clone(),
            action_digest,
            principal_id: request.actor.principal_id.clone(),
            surface: request.surface.clone(),
            resource_type,
            resource_id,
            expires_at,
            issuer: CANONICAL_GATE_ISSUER.to_string(),
            status: "pending".to_string(),
            created_at,
            tool_params: None,
        }
    }

    /// Attach the raw tool-call params (JSON) the run Paused on (S6d), so the resume
    /// entrypoint can re-execute the EXACT approved mutation. Returns `self` for a
    /// builder-style call right after [`PendingApprovalRequest::for_request`].
    pub fn with_tool_params(mut self, tool_params: Option<String>) -> Self {
        self.tool_params = tool_params;
        self
    }
}

/// Persist a pending approval request. The `approval_id` PRIMARY KEY makes a duplicate
/// nonce a fail-closed `Err` (a nonce is never silently reused).
pub fn persist_pending_request(conn: &Connection, req: &PendingApprovalRequest) -> Result<()> {
    conn.execute(
        "INSERT INTO pending_approval_request (
            approval_id, run_id, action, action_digest, principal_id, surface,
            resource_type, resource_id, expires_at, issuer, status, created_at, tool_params
         ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)",
        params![
            req.approval_id,
            req.run_id,
            req.action,
            req.action_digest,
            req.principal_id,
            req.surface,
            req.resource_type,
            req.resource_id,
            req.expires_at,
            req.issuer,
            req.status,
            req.created_at,
            req.tool_params,
        ],
    )?;
    Ok(())
}

/// Mark a pending request resolved (S6d), e.g. `consumed` after a successful resume or
/// `denied` after a refused one. Idempotent bookkeeping ONLY — the load-bearing
/// single-use guarantee is the gate's `consumed_approval` nonce store, which already
/// makes a second ingest of the same approval a replay-refused Deny regardless of this
/// status. Returns the number of rows updated (0 if the nonce is unknown).
pub fn set_pending_status(conn: &Connection, approval_id: &str, status: &str) -> Result<usize> {
    let n = conn.execute(
        "UPDATE pending_approval_request SET status = ?2 WHERE approval_id = ?1",
        params![approval_id, status],
    )?;
    Ok(n)
}

fn row_to_pending(row: &rusqlite::Row) -> rusqlite::Result<PendingApprovalRequest> {
    Ok(PendingApprovalRequest {
        approval_id: row.get(0)?,
        run_id: row.get(1)?,
        action: row.get(2)?,
        action_digest: row.get(3)?,
        principal_id: row.get(4)?,
        surface: row.get(5)?,
        resource_type: row.get(6)?,
        resource_id: row.get(7)?,
        expires_at: row.get(8)?,
        issuer: row.get(9)?,
        status: row.get(10)?,
        created_at: row.get(11)?,
        tool_params: row.get(12)?,
    })
}

const SELECT_COLS: &str = "approval_id, run_id, action, action_digest, principal_id, surface, \
     resource_type, resource_id, expires_at, issuer, status, created_at, tool_params";

/// Read a pending request by its `approval_id` nonce. `None` if absent.
pub fn get_pending_request(
    conn: &Connection,
    approval_id: &str,
) -> Result<Option<PendingApprovalRequest>> {
    let sql = format!("SELECT {SELECT_COLS} FROM pending_approval_request WHERE approval_id = ?1");
    let out = conn
        .query_row(&sql, params![approval_id], row_to_pending)
        .optional()?;
    Ok(out)
}

/// List the pending requests for a run, oldest first (so S6d can resume in order).
pub fn list_pending_requests_for_run(
    conn: &Connection,
    run_id: &str,
) -> Result<Vec<PendingApprovalRequest>> {
    let sql = format!(
        "SELECT {SELECT_COLS} FROM pending_approval_request WHERE run_id = ?1 \
         ORDER BY created_at, approval_id"
    );
    let mut stmt = conn.prepare(&sql)?;
    let rows = stmt.query_map(params![run_id], row_to_pending)?;
    let mut out = Vec::new();
    for r in rows {
        out.push(r?);
    }
    Ok(out)
}
