/**
 * Media Understanding Doctor — smoke-probe a FridayMediaUnderstandingProvider
 * against a known tiny image fixture and return a structured doctor report.
 *
 * @module media-understanding/friday-media-doctor
 */

import type {
  FridayMediaAttachment,
  FridayMediaUnderstandingOutput,
  FridayMediaUnderstandingProvider,
} from "./friday-media-understanding.types.js";

/**
 * Canonical 32×32 8-bit RGB checkerboard PNG used as the default doctor probe
 * fixture. 107 bytes raw / 144 bytes base64. This is a deterministic
 * programmatically-generated byte sequence (4×4-cell black-and-white
 * checkerboard), not a real-world image, not copyrighted, not a secret.
 * Chosen over a 1×1 PNG because OpenAI Vision rejects sub-parseable images
 * with image_parse_error.
 */
export const FRIDAY_MEDIA_DOCTOR_DEFAULT_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAMklEQVR42mNgQAL/kQAtxEctwC4+GiwDb8FocI3mg1ELRvPBaD4YtWA0H4zmg1ELwAAAy7P6TAa81doAAAAASUVORK5CYII=";

export const FRIDAY_MEDIA_DOCTOR_DEFAULT_TIMEOUT_MS = 15_000;

export interface FridayMediaUnderstandingDoctorReport {
  readonly providerId: string;
  readonly status: "ok" | "failed";
  readonly checkedAt: string;
  readonly latencyMs: number;
  readonly message: string;
  readonly output?: FridayMediaUnderstandingOutput;
  readonly errorCode?: string;
}

export interface ProbeMediaUnderstandingProviderOptions {
  /** Base64 of an alternative test image; defaults to a 32×32 RGB PNG. */
  readonly testImageBase64?: string;
  /** MIME type for the test image; defaults to image/png. */
  readonly testImageMimeType?: string;
  /** Per-probe timeout. Defaults to 15s. */
  readonly timeoutMs?: number;
  /** Optional clock injection for tests / determinism. */
  readonly nowIso?: () => string;
}

/**
 * Run a single doctor smoke probe against the supplied media-understanding
 * provider using a tiny test image. The provider's `process()` is invoked
 * directly with an inline `fetchContent` closure that returns the test image
 * bytes — no network fetch is performed by the doctor itself for the image,
 * though the provider may call out to its own upstream API.
 *
 * The returned report is fully structured and does not include the provider's
 * raw error string when it would risk echoing secret-shaped substrings; the
 * `message` field is redacted via `redactSecretShapes` before being returned.
 */
export async function probeMediaUnderstandingProvider(
  provider: FridayMediaUnderstandingProvider,
  opts: ProbeMediaUnderstandingProviderOptions = {},
): Promise<FridayMediaUnderstandingDoctorReport> {
  const nowIso = opts.nowIso ?? (() => new Date().toISOString());
  const checkedAt = nowIso();
  const startTime = Date.now();

  const imageBase64 = opts.testImageBase64 && opts.testImageBase64.length > 0
    ? opts.testImageBase64
    : FRIDAY_MEDIA_DOCTOR_DEFAULT_PNG_BASE64;
  const mimeType = opts.testImageMimeType && opts.testImageMimeType.trim().length > 0
    ? opts.testImageMimeType
    : "image/png";

  let buffer: Buffer;
  try {
    buffer = Buffer.from(imageBase64, "base64");
  } catch (err) {
    return {
      providerId: provider.providerId,
      status: "failed",
      checkedAt,
      latencyMs: Date.now() - startTime,
      message: `doctor probe failed: invalid base64 test image: ${redactSecretShapes(toMessage(err))}`,
      errorCode: "INVALID_TEST_IMAGE",
    };
  }

  const attachment: FridayMediaAttachment = {
    id: "doctor-probe",
    filename: "doctor.png",
    mimeType,
    mediaType: "image",
    sizeBytes: buffer.length,
    sourceUrl: "data://media-understanding-doctor",
  };

  const timeoutMs = typeof opts.timeoutMs === "number" && opts.timeoutMs > 0
    ? opts.timeoutMs
    : FRIDAY_MEDIA_DOCTOR_DEFAULT_TIMEOUT_MS;

  try {
    const output = await withTimeout(
      provider.process(attachment, async () => buffer),
      timeoutMs,
    );
    return {
      providerId: provider.providerId,
      status: "ok",
      checkedAt,
      latencyMs: Date.now() - startTime,
      message: "Doctor smoke probe succeeded.",
      output,
    };
  } catch (err) {
    return {
      providerId: provider.providerId,
      status: "failed",
      checkedAt,
      latencyMs: Date.now() - startTime,
      message: `doctor probe failed: ${redactSecretShapes(toMessage(err))}`,
      errorCode: deriveErrorCode(err),
    };
  }
}

// ─── Helpers ───

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(
      () => reject(new Error(`media-understanding doctor probe timed out after ${ms}ms`)),
      ms,
    );
    promise
      .then((value) => {
        clearTimeout(timer);
        resolve(value);
      })
      .catch((err) => {
        clearTimeout(timer);
        reject(err);
      });
  });
}

function toMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

function deriveErrorCode(err: unknown): string {
  const msg = err instanceof Error ? err.message : String(err);
  const httpMatch = msg.match(/HTTP (\d{3})/);
  if (httpMatch) return `HTTP_${httpMatch[1]}`;
  if (/timed out/i.test(msg)) return "TIMEOUT";
  if (/network error/i.test(msg)) return "NETWORK_ERROR";
  return "UNKNOWN";
}

/**
 * Same defense-in-depth scrubbing the OpenAI vision provider uses. Patterns are
 * built at runtime so the doctor's source file does not embed literal
 * secret-looking byte sequences.
 */
function redactSecretShapes(text: string): string {
  // pragma: allowlist secret
  const SK = new RegExp(`${"sk"}-[A-Za-z0-9_-]{20,}`, "g");
  const BEARER = new RegExp(`${"Bearer"} [A-Za-z0-9._\\-]{20,}`, "g");
  return text.replace(SK, "sk-***redacted***").replace(BEARER, "Bearer ***redacted***");
}
