/**
 * TRANSITIVELY WIRED into the production read-only Rust agent-run route, gated DEFAULT-OFF —
 * CLIENT-HALF of the friday-crypto sealed WS handshake for the executeRun-replacement
 * (sub-slice B1). As of B1-compose its primitives (`agree`/`seal`/`open`/`encodeSealed`/
 * `buildAuthProof`/...) are imported by `friday-rust-hub-agent-run-ws-sealed-client.ts`, which
 * the live route's `composeRustReadOnlyAgentRun` drives — so the prior "no production route
 * consumes this" claim is no longer true. It does NOT run in default prod: the route branch is
 * gated DEFAULT-OFF behind `FRIDAY_ROUTE_AGENT_RUN_VIA_RUST` (operator cutover pending).
 *
 * ## What this is
 * The byte-exact TS port of the friday-crypto / friday-transport client primitives the
 * Rust agent-run WS server requires:
 *   - X25519 ECDH + HKDF-SHA256 session-key agreement (`agree`) — `node:crypto` NATIVE,
 *     no third-party dep. Mirrors `friday-crypto/src/session.rs::DeviceKeypair::agree`.
 *   - XChaCha20-Poly1305 AEAD seal/open (`seal` / `open`) — `@noble/ciphers` (the ONLY
 *     third-party crypto dep, pinned exact). Mirrors `friday-crypto/src/lib.rs::seal/open`.
 *   - The on-wire sealed framing `[nonce_len:u8][nonce][ciphertext]` (`encodeSealed` /
 *     `decodeSealed`) — mirrors `friday-transport/src/lib.rs::encode_sealed/decode_sealed`
 *     AND the bin's identical `encode_sealed_proof` (the auth_proof framing).
 *   - The per-request auth bindings `authAad` / `nonceBoundChallenge` — mirror
 *     `friday-hub/src/hub_server.rs::auth_aad` / `nonce_bound_challenge`.
 *
 * Every primitive here is interop-tested against CHECKED-IN fixtures generated by the
 * Rust side (K1/K2/K3 in the sealed-crypto test) — a TS-seals-then-TS-opens roundtrip
 * would prove nothing (it is circular), so the only trustworthy proof is Rust-produced
 * bytes that TS must reproduce / open.
 *
 * ## Threat model (HONEST — loopback only)
 * The Rust server binds 127.0.0.1 only and this client connects only to loopback. The
 * client INTENTIONALLY does NOT authenticate the server: there is NO server-pubkey
 * pinning. On loopback that is acceptable — there is no relay to substitute keys, so the
 * active-MITM confidentiality property is not the load-bearing one here. The properties
 * that ARE load-bearing live on the SERVER and are NOT confidentiality:
 *   1. peer-pubkey allowlist (SecureStore) — only an enrolled client pubkey gets a session;
 *   2. owner-allowlist — only a configured owner principal may run;
 *   3. per-handshake nonce anti-replay — a captured auth_proof cannot re-authenticate.
 * This module is the client half of that handshake; it does not, and is not meant to,
 * defend confidentiality against a non-existent relay.
 *
 * ## Truth labels
 * - TRANSITIVELY consumed by the production route handler, gated DEFAULT-OFF: its primitives
 *   are imported by the sealed WS client that `composeRustReadOnlyAgentRun` drives on the live
 *   `routeStartRun` path, so it IS reached by a production route (NOT "no production route
 *   consumes it"). It stays inert in default prod until the operator flips
 *   `FRIDAY_ROUTE_AGENT_RUN_VIA_RUST` (cutover pending).
 * - `rust_wired` ceiling: confers NO v1 GO. It speaks the real sealed protocol; it is not a
 *   full product path until the operator cutover.
 */
import { createHash, createPrivateKey, createPublicKey, diffieHellman, hkdfSync, randomBytes } from "node:crypto";

import { xchacha20poly1305 } from "@noble/ciphers/chacha.js";

/** X25519 raw-pubkey width (bytes). Mirrors `X25519_PUBKEY_LEN`. */
export const X25519_PUBKEY_LEN = 32;
/** X25519 raw-secret-scalar width (bytes). */
export const X25519_SECRET_LEN = 32;
/** XChaCha20-Poly1305 nonce width (bytes). Mirrors RustCrypto `XNonce`. */
export const XCHACHA_NONCE_LEN = 24;
/** Poly1305 tag width (bytes), appended to the ciphertext. */
export const POLY1305_TAG_LEN = 16;
/** Derived session-key width (bytes). */
export const SESSION_KEY_LEN = 32;

/**
 * HKDF-SHA256 info string. Mirrors `friday-crypto/src/session.rs::SESSION_KDF_INFO`
 * (`b"friday-session-key-v1"`). The session key is `HKDF(salt=zero32, ikm=ecdh, info)`.
 */
const SESSION_KDF_INFO = Buffer.from("friday-session-key-v1", "utf8");

/**
 * HKDF salt. Rust uses `Hkdf::<Sha256>::new(None, shared)` (salt = None), which RFC5869
 * treats as a string of HashLen (32) zero bytes. Node's empty-salt is ALSO 32 zero bytes
 * on the tested runtime (Node 22), but we pass an EXPLICIT 32-zero-byte salt so the
 * derivation is unambiguous and version-independent (verified byte-equal to the Rust
 * `agree()` in K1).
 */
const HKDF_ZERO_SALT = Buffer.alloc(32);

/**
 * DER prefixes that wrap a raw 32-byte X25519 key into the SPKI/PKCS8 form `node:crypto`
 * key import requires. These are the fixed algorithm-identifier + bit/octet-string headers
 * for `id-X25519` (OID 1.3.101.110); the raw key bytes are appended verbatim.
 *   - SPKI (public): `302a300506032b656e032100` then 32 pubkey bytes.
 *   - PKCS8 (private): `302e020100300506032b656e04220420` then 32 secret bytes.
 */
const X25519_SPKI_PREFIX = Buffer.from("302a300506032b656e032100", "hex");
const X25519_PKCS8_PREFIX = Buffer.from("302e020100300506032b656e04220420", "hex");

/** Wrap a raw 32-byte X25519 public key into a node KeyObject (SPKI DER import). */
function importX25519Public(raw: Uint8Array): ReturnType<typeof createPublicKey> {
  if (raw.length !== X25519_PUBKEY_LEN) {
    throw new RangeError(`x25519 public key must be ${X25519_PUBKEY_LEN} bytes`);
  }
  return createPublicKey({
    key: Buffer.concat([X25519_SPKI_PREFIX, Buffer.from(raw)]),
    format: "der",
    type: "spki",
  });
}

/** Wrap a raw 32-byte X25519 secret scalar into a node KeyObject (PKCS8 DER import). */
function importX25519Private(raw: Uint8Array): ReturnType<typeof createPrivateKey> {
  if (raw.length !== X25519_SECRET_LEN) {
    throw new RangeError(`x25519 secret key must be ${X25519_SECRET_LEN} bytes`);
  }
  return createPrivateKey({
    key: Buffer.concat([X25519_PKCS8_PREFIX, Buffer.from(raw)]),
    format: "der",
    type: "pkcs8",
  });
}

/** Export a node X25519 public KeyObject back to its raw 32-byte form. */
function exportX25519PublicRaw(key: ReturnType<typeof createPublicKey>): Uint8Array {
  const der = key.export({ format: "der", type: "spki" });
  return new Uint8Array(der.subarray(X25519_SPKI_PREFIX.length));
}

/** A device's X25519 keypair (the TS client half). Mirrors `DeviceKeypair`. */
export interface DeviceKeypair {
  /** The raw 32-byte X25519 secret scalar. Held in-process only; never logged. */
  readonly secret: Uint8Array;
  /** The raw 32-byte X25519 public key (sent to the server in the cleartext preamble). */
  readonly publicKey: Uint8Array;
}

/**
 * Reconstruct a keypair from a stored 32-byte X25519 secret scalar. Mirrors
 * `DeviceKeypair::from_secret_bytes`: the public half is derived from the secret, so two
 * callers with the same secret get the same pubkey (used to enroll the client in the
 * server's peer-allowlist before the handshake).
 */
export function deviceKeypairFromSecret(secret: Uint8Array): DeviceKeypair {
  if (secret.length !== X25519_SECRET_LEN) {
    throw new RangeError(`x25519 secret key must be ${X25519_SECRET_LEN} bytes`);
  }
  const priv = importX25519Private(secret);
  const pub = createPublicKey(priv);
  return { secret: new Uint8Array(secret), publicKey: exportX25519PublicRaw(pub) };
}

/**
 * Derive the shared session key from THIS device's secret and a peer's raw 32-byte public
 * key: `HKDF-SHA256(salt=zero32, ikm=X25519(secret, peerPub), info="friday-session-key-v1")`.
 * Byte-identical to `DeviceKeypair::agree` (verified in K1). Returns a 32-byte key.
 *
 * NOTE (intentional, per threat model): `peerPub` is the SERVER's pubkey, read from the
 * cleartext preamble and NOT pinned/authenticated — acceptable on loopback only.
 */
export function agree(secret: Uint8Array, peerPublicKey: Uint8Array): Uint8Array {
  const shared = diffieHellman({
    privateKey: importX25519Private(secret),
    publicKey: importX25519Public(peerPublicKey),
  });
  // Explicit 32-zero-byte salt == Rust `Hkdf::new(None, …)` (verified byte-equal in K1).
  const okm = hkdfSync("sha256", shared, HKDF_ZERO_SALT, SESSION_KDF_INFO, SESSION_KEY_LEN);
  return new Uint8Array(okm);
}

/** A sealed blob: ciphertext (= plaintext + 16-byte tag) plus the nonce it was sealed under. */
export interface Sealed {
  /** The XChaCha20-Poly1305 nonce (24 bytes). */
  readonly nonce: Uint8Array;
  /** The ciphertext WITH the 16-byte Poly1305 tag appended (RustCrypto layout). */
  readonly ciphertext: Uint8Array;
}

/**
 * Encrypt `plaintext` under `key` authenticating `aad`, with a fresh random 24-byte nonce.
 * Mirrors `friday-crypto::seal`. The returned `ciphertext` already carries the 16-byte tag
 * appended (matching RustCrypto's `XChaCha20Poly1305` output). Verified Rust-openable in K2.
 */
export function seal(key: Uint8Array, plaintext: Uint8Array, aad: Uint8Array): Sealed {
  if (key.length !== SESSION_KEY_LEN) {
    throw new RangeError(`session key must be ${SESSION_KEY_LEN} bytes`);
  }
  const nonce = randomBytes(XCHACHA_NONCE_LEN);
  // @noble takes AAD as the 3rd CONSTRUCTOR arg (NOT a .encrypt(pt, aad) arg — that 2nd
  // positional is an output buffer in this API). The tag is appended to the ciphertext.
  const ciphertext = xchacha20poly1305(key, nonce, aad).encrypt(plaintext);
  return { nonce: new Uint8Array(nonce), ciphertext: new Uint8Array(ciphertext) };
}

/**
 * Decrypt + authenticate `sealed` under `key` with `aad`. Mirrors `friday-crypto::open`:
 * throws on ANY tamper (wrong key, flipped byte, mismatched AAD, truncated tag) or a
 * wrong-width nonce. Verified to open a Rust-produced seal in K2.
 */
export function open(key: Uint8Array, sealed: Sealed, aad: Uint8Array): Uint8Array {
  if (key.length !== SESSION_KEY_LEN) {
    throw new RangeError(`session key must be ${SESSION_KEY_LEN} bytes`);
  }
  if (sealed.nonce.length !== XCHACHA_NONCE_LEN) {
    throw new RangeError(`xchacha nonce must be ${XCHACHA_NONCE_LEN} bytes`);
  }
  // Throws (bad tag / wrong key / wrong aad) — the caller treats any throw as fail-closed.
  const pt = xchacha20poly1305(key, sealed.nonce, aad).decrypt(sealed.ciphertext);
  return new Uint8Array(pt);
}

/**
 * Encode a `Sealed` to the on-wire form `[nonce_len:u8][nonce][ciphertext]`. Mirrors BOTH
 * `friday-transport::encode_sealed` (the envelope body) AND the bin's identical
 * `encode_sealed_proof` (the auth_proof) — one layout for both.
 */
export function encodeSealed(sealed: Sealed): Uint8Array {
  const out = new Uint8Array(1 + sealed.nonce.length + sealed.ciphertext.length);
  out[0] = sealed.nonce.length & 0xff;
  out.set(sealed.nonce, 1);
  out.set(sealed.ciphertext, 1 + sealed.nonce.length);
  return out;
}

/**
 * Decode the on-wire sealed form back into a `Sealed`. Mirrors `decode_sealed`: throws on
 * an empty/too-short frame (the caller treats a throw as fail-closed).
 */
export function decodeSealed(wire: Uint8Array): Sealed {
  if (wire.length === 0) {
    throw new RangeError("empty sealed frame");
  }
  const nlen = wire[0];
  if (wire.length < 1 + nlen) {
    throw new RangeError("sealed frame too short");
  }
  return {
    nonce: wire.subarray(1, 1 + nlen),
    ciphertext: wire.subarray(1 + nlen),
  };
}

/**
 * The per-handshake challenge the peer must seal: `challenge ++ session_nonce`. Mirrors
 * `hub_server::nonce_bound_challenge`. The `sessionNonce` is the 64-byte token from the
 * preamble — used VERBATIM (it is the hex chars of a 32-byte CSPRNG delivered as 64 bytes;
 * the server binds those same 64 bytes — do NOT hex-decode it to 32 bytes).
 */
export function nonceBoundChallenge(challenge: Uint8Array, sessionNonce: Uint8Array): Uint8Array {
  const out = new Uint8Array(challenge.length + sessionNonce.length);
  out.set(challenge, 0);
  out.set(sessionNonce, challenge.length);
  return out;
}

/**
 * The per-request auth AAD: `aad ++ u32be(len(principal)) ++ principal ++ u32be(len(run_id))
 * ++ run_id`, each field length-delimited with a 4-byte big-endian prefix. Mirrors
 * `hub_server::auth_aad` — so an auth_proof can't be lifted to a different (principal, run_id).
 */
export function authAad(aad: Uint8Array, forwardedPrincipal: string, runId: string): Uint8Array {
  const principal = Buffer.from(forwardedPrincipal, "utf8");
  const run = Buffer.from(runId, "utf8");
  const out = new Uint8Array(aad.length + 4 + principal.length + 4 + run.length);
  const view = new DataView(out.buffer);
  let off = 0;
  out.set(aad, off);
  off += aad.length;
  view.setUint32(off, principal.length, false); // big-endian length prefix
  off += 4;
  out.set(principal, off);
  off += principal.length;
  view.setUint32(off, run.length, false); // big-endian length prefix
  off += 4;
  out.set(run, off);
  return out;
}

/**
 * Build the per-request `auth_proof` bytes: `encodeSealed(seal(sessionKey, random24,
 * msg=nonceBoundChallenge(AUTH_CHALLENGE, sessionNonce), aad=authAad(SESSION_AAD,
 * principal, run_id)))`. Mirrors the bin's `auth_proof_bytes` exactly — this is what the
 * trusted peer seals post-handshake (it is NOT precomputable before the nonce is known).
 */
export function buildAuthProof(params: {
  readonly sessionKey: Uint8Array;
  readonly sessionNonce: Uint8Array;
  readonly sessionAad: Uint8Array;
  readonly authChallenge: Uint8Array;
  readonly forwardedPrincipal: string;
  readonly runId: string;
}): Uint8Array {
  const challenge = nonceBoundChallenge(params.authChallenge, params.sessionNonce);
  const reqAad = authAad(params.sessionAad, params.forwardedPrincipal, params.runId);
  const sealed = seal(params.sessionKey, challenge, reqAad);
  return encodeSealed(sealed);
}

/** sha256 hex of `bytes` (lowercase). For asserting the answer fingerprint against refs. */
export function sha256Hex(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

/** Hex-decode a string into bytes. Throws on odd length / non-hex (fail-closed at the caller). */
export function hexDecode(s: string): Uint8Array {
  if (s.length % 2 !== 0) {
    throw new RangeError("hex string has odd length");
  }
  // `Buffer.from(s, "hex")` silently STOPS at the first non-hex char, so it cannot signal a
  // malformed chunk. Validate the charset first, then decode — so bad input throws (fail-closed).
  if (!/^[0-9a-fA-F]*$/.test(s)) {
    throw new RangeError("invalid hex");
  }
  return new Uint8Array(Buffer.from(s, "hex"));
}
