import Foundation

/// **B1 KAT FIXTURES — Rust-produced gold byte vectors**, ported VERBATIM (hex unchanged)
/// from the checked-in TS fixture
/// `test/unit/api/mission-spine/fixtures/b1-rust-handshake-kat.ts`.
///
/// Provenance (from the TS fixture header): generated by the throwaway external Rust
/// project `b1-kat-gen`, which path-deps the rust-core crates and calls ONLY the real
/// `pub` `friday-crypto` / `friday-hub` API (the SAME functions the production server
/// uses) — so these anchor on the real Rust crates, NOT a reimplementation. `rust-core` is
/// byte-untouched by the generator.
///
/// These are NON-SECRET test vectors (deterministic fixed test scalars + Rust-produced
/// sealed blobs). The Swift KATs make Swift REPRODUCE these Rust bytes (K3) or OPEN these
/// Rust seals (K1/K2) — a Swift-seals-then-Swift-opens roundtrip would be CIRCULAR (it
/// proves nothing about Rust interop), so the only trustworthy proof is Rust-produced
/// bytes Swift must reproduce / open. This is exactly the discipline the TS sealed-crypto
/// test header documents.
///
/// NOTE: the `SESSION_AAD` / `AUTH_CHALLENGE` constants here are the WRITE path's
/// (`friday:execrun:ws:s-c:...`) — the generator's. They are only used by K3 to pin the
/// `auth_aad` / `nonce_bound_challenge` *construction* (which is input-generic). The READ
/// path's own constants (`friday:ui-read-seam:ws:s-r1:...`) are exercised separately in the
/// read-path KAT, which reuses the SAME Rust-anchored construction.
enum B1KAT {
  enum constants {
    static let SESSION_AAD = "6672696461793a6578656372756e3a77733a732d633a6167656e742d72756e2d73657373696f6e3a6161643a7631" // pragma: allowlist secret
    static let AUTH_CHALLENGE = "6672696461793a6578656372756e3a77733a732d633a6175746865642d72756e3a6368616c6c656e67653a7631" // pragma: allowlist secret
    static let SESSION_KDF_INFO = "6672696461792d73657373696f6e2d6b65792d7631" // pragma: allowlist secret
  }

  enum k1Agree {
    static let clientSecret = "070b0d1113171d1f25292b2f353b3d4347494f53596165676b6d717f83898b95" // pragma: allowlist secret
    static let clientPub = "98197787aca624cdc9b2ec6eeda9e7d673a8e74d4bb2528334f6233ee7449a1a" // pragma: allowlist secret
    static let serverSecret = "020305070b0d1113171d1f25292b2f353b3d4347494f53596165676b6d717f83" // pragma: allowlist secret
    static let serverPub = "e9304b60e0ca3a0117ce37a6c704825f6a1f6ddd056644f1544db2ea9e639363" // pragma: allowlist secret
    static let plaintext = "4b312d41475245452d53454e54494e454c" // pragma: allowlist secret
    static let aad = "6b312d616164" // pragma: allowlist secret
    static let sealedWire = "186c7a9e95cf9fe494c818f51e27a013a0cd38fa3ccde9fb280420c88d85b7c1ba9e3e9135fcc7409a0b5b5b340f8afac8df68e31dbce4e35951" // pragma: allowlist secret
  }

  enum k2Aead {
    static let key = "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f" // pragma: allowlist secret
    static let plaintext = "4b322d414541442d4652414d494e472d53454e54494e454c" // pragma: allowlist secret
    static let aad = "6672696461793a6b323a6b6e6f776e2d616164" // pragma: allowlist secret
    static let sealedWire = "18a28e1a2ee9e8284a3be0749ba41ab68ea6960c9b93912d4467c8ad12624e226619bfdf9a2cea836b87887db6d2bdaba202f093d59aa3405725b719c8ad5fecbb" // pragma: allowlist secret
  }

  enum k3Auth {
    static let principal = "principal:owner-allowlisted" // pragma: allowlist secret
    static let runId = "run-k3-fixture"
    static let authAad = "6672696461793a6578656372756e3a77733a732d633a6167656e742d72756e2d73657373696f6e3a6161643a76310000001b7072696e636970616c3a6f776e65722d616c6c6f776c69737465640000000e72756e2d6b332d66697874757265" // pragma: allowlist secret
    static let sessionNonce = "30313233343536373839616263646566303132333435363738396162636465663031323334353637383961626364656630313233343536373839616263646566" // pragma: allowlist secret
    static let nonceBoundChallenge = "6672696461793a6578656372756e3a77733a732d633a6175746865642d72756e3a6368616c6c656e67653a763130313233343536373839616263646566303132333435363738396162636465663031323334353637383961626364656630313233343536373839616263646566" // pragma: allowlist secret
  }
}
