import XCTest
@testable import FridayRustClient

/// **THE deliverable — byte-asserted Swift↔Rust crypto-parity KATs.**
///
/// These prove the Swift crypto stack (CryptoKit X25519+HKDF-SHA256 + swift-sodium
/// XChaCha20-Poly1305) is BYTE-IDENTICAL to the Rust/TS side, against Rust-PRODUCED gold
/// vectors (`B1KAT`, generated by the real `pub friday-crypto`/`friday-hub` API). The
/// server is SILENT on a crypto mismatch, so byte-parity is mandatory and is what these
/// KATs lock down OFFLINE (no running server needed — that is the point).
///
/// Provenance discipline (mirrors the TS sealed-crypto test): a Swift-seals-then-Swift-opens
/// roundtrip is CIRCULAR. So K1/K2 OPEN Rust-produced seals (a wrong Swift key/AAD fails the
/// Poly1305 tag → there is no way the bytes differ yet `open` succeeds), and K3 REPRODUCES
/// the exact Rust `auth_aad` / `nonce_bound_challenge` bytes.
final class KATTests: XCTestCase {

  private func hex(_ s: String) throws -> [UInt8] { try Hex.decode(s) }
  private func utf8(_ b: [UInt8]) -> String { String(decoding: b, as: UTF8.self) }

  // MARK: K1 — X25519 ECDH + HKDF-SHA256 (the session-key derivation)

  /// K1 pubkey: Swift `DeviceKeypair(secretBytes:)` derives the SAME 32-byte X25519 public
  /// key as Rust `DeviceKeypair::from_secret_bytes` — a DIRECT byte assertion. Proves the
  /// X25519 secret→public derivation interops (CryptoKit Curve25519 == x25519-dalek).
  func testK1_pubkeyByteIdenticalToRust() throws {
    let client = try FridayCrypto.DeviceKeypair(secretBytes: hex(B1KAT.k1Agree.clientSecret))
    XCTAssertEqual(Hex.encode(client.publicKey), B1KAT.k1Agree.clientPub,
                   "Swift-derived X25519 pubkey must byte-match the Rust-derived pubkey")
    // Also the server fixture keypair (used as the agree() peer below).
    let server = try FridayCrypto.DeviceKeypair(secretBytes: hex(B1KAT.k1Agree.serverSecret))
    XCTAssertEqual(Hex.encode(server.publicKey), B1KAT.k1Agree.serverPub)
  }

  /// K1: Swift `agree()` derives the SAME 32-byte session key as Rust `DeviceKeypair::agree`
  /// — PROVEN by OPENING a blob Rust sealed under the agreed key. A successful open IS the
  /// key-equality proof: a wrong Swift key would fail the Poly1305 tag. This validates the
  /// FULL stack: X25519 ECDH + HKDF-SHA256(salt=zero32, info="friday-session-key-v1").
  func testK1_agreeDerivesSameSessionKey_opensRustSeal() throws {
    let client = try FridayCrypto.DeviceKeypair(secretBytes: hex(B1KAT.k1Agree.clientSecret))
    let sessionKey = try client.agree(peerPublicKey: hex(B1KAT.k1Agree.serverPub))
    XCTAssertEqual(sessionKey.count, 32)

    let sealed = try FridayCrypto.decodeSealed(hex(B1KAT.k1Agree.sealedWire))
    let opened = try FridayCrypto.open(key: sessionKey, sealed: sealed, aad: hex(B1KAT.k1Agree.aad))
    XCTAssertEqual(opened, try hex(B1KAT.k1Agree.plaintext))
    XCTAssertEqual(utf8(opened), "K1-AGREE-SENTINEL",
                   "opening a Rust seal under the Swift-derived key proves byte-identical key agreement")
  }

  /// K1 negative: a perturbed server pubkey yields a DIFFERENT key that CANNOT open the Rust
  /// blob — confirms the open above is load-bearing (not vacuously passing).
  func testK1_wrongServerPubkeyCannotOpen() throws {
    let client = try FridayCrypto.DeviceKeypair(secretBytes: hex(B1KAT.k1Agree.clientSecret))
    var wrongServerPub = try hex(B1KAT.k1Agree.serverPub)
    wrongServerPub[0] ^= 0x01
    let wrongKey = try client.agree(peerPublicKey: wrongServerPub)
    let sealed = try FridayCrypto.decodeSealed(hex(B1KAT.k1Agree.sealedWire))
    XCTAssertThrowsError(try FridayCrypto.open(key: wrongKey, sealed: sealed, aad: hex(B1KAT.k1Agree.aad))) {
      XCTAssertEqual($0 as? FridayCryptoError, .openFailed)
    }
  }

  // MARK: K2 — XChaCha20-Poly1305 AEAD + on-wire `[nonce_len][nonce][ciphertext]` framing

  /// K2: Swift `decodeSealed` + `open` recovers the plaintext from a blob Rust sealed under a
  /// KNOWN 32-byte key + KNOWN AAD. Isolates the AEAD + on-wire framing under a controlled
  /// key — proves swift-sodium's XChaCha20-Poly1305 (24-byte nonce) byte-matches RustCrypto's
  /// `XChaCha20Poly1305`, and that the framing's first byte IS the 24-byte nonce length.
  func testK2_decodeAndOpenRustSeal() throws {
    let sealed = try FridayCrypto.decodeSealed(hex(B1KAT.k2Aead.sealedWire))
    XCTAssertEqual(sealed.nonce.count, 24, "the on-wire nonce_len byte must decode to a 24-byte XChaCha nonce")
    let opened = try FridayCrypto.open(key: hex(B1KAT.k2Aead.key), sealed: sealed, aad: hex(B1KAT.k2Aead.aad))
    XCTAssertEqual(utf8(opened), "K2-AEAD-FRAMING-SENTINEL")
  }

  /// K2 negative: a tampered AAD makes the Rust seal FAIL to open (AEAD binding). Confirms
  /// the AAD is authenticated, not ignored.
  func testK2_tamperedAadFailsToOpen() throws {
    let sealed = try FridayCrypto.decodeSealed(hex(B1KAT.k2Aead.sealedWire))
    var wrongAad = try hex(B1KAT.k2Aead.aad)
    wrongAad[0] ^= 0x01
    XCTAssertThrowsError(try FridayCrypto.open(key: hex(B1KAT.k2Aead.key), sealed: sealed, aad: wrongAad)) {
      XCTAssertEqual($0 as? FridayCryptoError, .openFailed)
    }
  }

  /// K2 roundtrip: a Swift seal under the known key opens back (encode/decode symmetry of the
  /// framing). NOT a parity proof on its own (it is circular) — it pins the Swift framing's
  /// internal consistency; K2 above is the Rust-anchored proof.
  func testK2_swiftSealRoundTrips() throws {
    let key = try hex(B1KAT.k2Aead.key)
    let pt = try hex(B1KAT.k2Aead.plaintext)
    let aad = try hex(B1KAT.k2Aead.aad)
    let wire = FridayCrypto.encodeSealed(try FridayCrypto.seal(key: key, plaintext: pt, aad: aad))
    let opened = try FridayCrypto.open(key: key, sealed: FridayCrypto.decodeSealed(wire), aad: aad)
    XCTAssertEqual(utf8(opened), "K2-AEAD-FRAMING-SENTINEL")
    // The first wire byte is the 24-byte nonce length (the framing the server speaks).
    XCTAssertEqual(wire[0], 24)
  }

  // MARK: K3 — auth bindings (per-request AAD + nonce-bound challenge)

  /// K3: Swift `authAad` reproduces the EXACT Rust `auth_aad` bytes — the length-delimited
  /// binding `aad || BE32(len(principal)) || principal || BE32(len(ctx)) || ctx`. A DIRECT
  /// byte assertion against the Rust-produced vector. Validates that an `auth_proof` cannot
  /// be lifted to a different `(principal, request_id)`.
  func testK3_authAadByteIdenticalToRust() throws {
    let sessionAad = try hex(B1KAT.constants.SESSION_AAD)
    let built = FridayCrypto.authAad(sessionAad,
                                     forwardedPrincipal: B1KAT.k3Auth.principal,
                                     boundContext: Array(B1KAT.k3Auth.runId.utf8))
    XCTAssertEqual(Hex.encode(built), B1KAT.k3Auth.authAad)
  }

  /// K3: Swift `nonceBoundChallenge` reproduces the EXACT Rust `nonce_bound_challenge` bytes.
  /// The 64-byte session nonce is bound VERBATIM (NOT hex-decoded to 32 bytes).
  func testK3_nonceBoundChallengeByteIdenticalToRust() throws {
    let authChallenge = try hex(B1KAT.constants.AUTH_CHALLENGE)
    let sessionNonce = try hex(B1KAT.k3Auth.sessionNonce)
    XCTAssertEqual(sessionNonce.count, 64, "the session nonce is 64 bytes (hex of 32 CSPRNG), bound verbatim")
    let built = FridayCrypto.nonceBoundChallenge(authChallenge, sessionNonce: sessionNonce)
    XCTAssertEqual(Hex.encode(built), B1KAT.k3Auth.nonceBoundChallenge)
  }

  /// K3 proof construction: `buildAuthProof` produces a blob that opens to the nonce-bound
  /// challenge under the auth AAD — proves it wires `authAad`/`nonceBoundChallenge`/`seal`/
  /// `encodeSealed` together correctly (the TRUE Rust-accepts-the-proof check is the deferred
  /// live e2e). Mirrors the TS `buildAuthProof` self-consistency KAT.
  func testK3_buildAuthProofOpensToTheNonceBoundChallenge() throws {
    let sessionKey = try hex(B1KAT.k2Aead.key)
    let sessionAad = try hex(B1KAT.constants.SESSION_AAD)
    let authChallenge = try hex(B1KAT.constants.AUTH_CHALLENGE)
    let sessionNonce = try hex(B1KAT.k3Auth.sessionNonce)
    let proofWire = try FridayCrypto.buildAuthProof(
      sessionKey: sessionKey,
      sessionNonce: sessionNonce,
      sessionAad: sessionAad,
      authChallenge: authChallenge,
      forwardedPrincipal: B1KAT.k3Auth.principal,
      boundContext: Array(B1KAT.k3Auth.runId.utf8)
    )
    let reqAad = FridayCrypto.authAad(sessionAad,
                                      forwardedPrincipal: B1KAT.k3Auth.principal,
                                      boundContext: Array(B1KAT.k3Auth.runId.utf8))
    let opened = try FridayCrypto.open(key: sessionKey,
                                       sealed: FridayCrypto.decodeSealed(proofWire),
                                       aad: reqAad)
    let expected = FridayCrypto.nonceBoundChallenge(authChallenge, sessionNonce: sessionNonce)
    XCTAssertEqual(opened, expected)
  }

  // MARK: Read-path auth binding — the SAME Rust-anchored construction, read constants

  /// The read seam uses the SAME `auth_aad` / `nonce_bound_challenge` construction (already
  /// byte-pinned to Rust in K3) but with the READ constants and `bound_context = request_id`
  /// (not run_id). Since the construction is input-generic and Rust-anchored, this asserts
  /// the read client binds the READ session AAD / challenge correctly, and that the read
  /// `auth_proof` opens back to the read nonce-bound challenge under the read auth AAD. The
  /// length-delimited framing means swapping principal OR request_id changes the AAD (a proof
  /// cannot be lifted) — asserted by the negative below.
  func testReadPath_authProofConstruction() throws {
    let sessionKey = try hex(B1KAT.k2Aead.key)
    let sessionNonce = try hex(B1KAT.k3Auth.sessionNonce) // any 64-byte nonce
    let principal = "principal:read-owner-allowlisted"
    let requestId = "req-roundtrip-1"

    // The read-path AAD/challenge use the read constants (`friday:ui-read-seam:ws:s-r1:...`).
    let readAad = FridayCrypto.authAad(readSessionAad, forwardedPrincipal: principal, boundContext: Array(requestId.utf8))
    let readChallenge = FridayCrypto.nonceBoundChallenge(readAuthChallenge, sessionNonce: sessionNonce)

    let proofWire = try FridayCrypto.buildAuthProof(
      sessionKey: sessionKey,
      sessionNonce: sessionNonce,
      sessionAad: readSessionAad,
      authChallenge: readAuthChallenge,
      forwardedPrincipal: principal,
      boundContext: Array(requestId.utf8)
    )
    let opened = try FridayCrypto.open(key: sessionKey, sealed: FridayCrypto.decodeSealed(proofWire), aad: readAad)
    XCTAssertEqual(opened, readChallenge, "the read auth_proof opens to the read nonce-bound challenge")

    // The read SESSION_AAD bytes match the Rust bin constant exactly.
    XCTAssertEqual(utf8(readSessionAad), "friday:ui-read-seam:ws:s-r1:read-projection-session:aad:v1")
    XCTAssertEqual(utf8(readAuthChallenge), "friday:ui-read-seam:ws:s-r1:read-projection:challenge:v1")
  }

  /// Read-path anti-lift negative: a proof sealed for `(principalA, requestA)` does NOT open
  /// under the AAD for a DIFFERENT principal or request id — the length-delimited binding
  /// (`("ab","c") != ("a","bc")`) is what gives reads the anti-lift guarantee.
  func testReadPath_proofCannotBeLiftedToAnotherRequest() throws {
    let sessionKey = try hex(B1KAT.k2Aead.key)
    let sessionNonce = try hex(B1KAT.k3Auth.sessionNonce)
    let principal = "principal:read-owner-allowlisted"

    let proofWire = try FridayCrypto.buildAuthProof(
      sessionKey: sessionKey, sessionNonce: sessionNonce,
      sessionAad: readSessionAad, authChallenge: readAuthChallenge,
      forwardedPrincipal: principal, boundContext: Array("req-A".utf8)
    )
    // Opening under a DIFFERENT request id's AAD must fail (the proof is bound to "req-A").
    let liftedAad = FridayCrypto.authAad(readSessionAad, forwardedPrincipal: principal, boundContext: Array("req-B".utf8))
    XCTAssertThrowsError(try FridayCrypto.open(key: sessionKey, sealed: FridayCrypto.decodeSealed(proofWire), aad: liftedAad))
    // And under a DIFFERENT principal's AAD.
    let liftedPrincipalAad = FridayCrypto.authAad(readSessionAad, forwardedPrincipal: "principal:attacker", boundContext: Array("req-A".utf8))
    XCTAssertThrowsError(try FridayCrypto.open(key: sessionKey, sealed: FridayCrypto.decodeSealed(proofWire), aad: liftedPrincipalAad))
  }

  // MARK: Framing edge cases (fail-closed, never a panic)

  /// `decodeSealed` of an empty/truncated wire is a thrown error, never a crash — mirrors the
  /// Rust `decode_sealed_proof` returning `None` on malformed input.
  func testFraming_malformedWireFailsClosed() {
    XCTAssertThrowsError(try FridayCrypto.decodeSealed([])) {
      XCTAssertEqual($0 as? FridayCryptoError, .malformedSealedFrame)
    }
    // nonce_len says 5 but only 2 bytes follow.
    XCTAssertThrowsError(try FridayCrypto.decodeSealed([5, 1, 2])) {
      XCTAssertEqual($0 as? FridayCryptoError, .malformedSealedFrame)
    }
  }

  /// Hex decode rejects odd-length / non-hex (fail-closed), mirroring the bin's `hex_decode`.
  func testHex_rejectsMalformed() {
    XCTAssertThrowsError(try Hex.decode("abc"))   // odd length
    XCTAssertThrowsError(try Hex.decode("zz"))    // non-hex
    XCTAssertEqual(try Hex.decode("00ff10"), [0x00, 0xff, 0x10])
    XCTAssertEqual(Hex.encode([0x00, 0xff, 0x10]), "00ff10")
  }
}
