import XCTest
@testable import FridayRustClient

/// **THE write-path deliverable — byte-asserted Swift↔Rust/TS parity for the WRITE / agent-run
/// seam.** These prove the Swift WRITE client speaks the SAME bytes as the Rust agent-run server
/// (`bin/hub_agent_run_server.rs`) + the TS courier
/// (`friday-rust-hub-agent-run-ws-sealed-client.ts`), using the WRITE constants + flow.
///
/// Provenance discipline (mirrors #677's `KATTests`): the WRITE auth_aad parity reuses the SAME
/// Rust-PRODUCED gold vectors as the read path — the B1KAT fixtures were generated with the WRITE
/// constants (`B1KAT.constants.SESSION_AAD` = `friday:execrun:ws:s-c:agent-run-session:aad:v1`,
/// `B1KAT.k3Auth.runId="run-k3-fixture"` as the bound_context, `B1KAT.k3Auth.authAad` the
/// Rust-produced output), so the WRITE path's `auth_aad`/`nonce_bound_challenge` are byte-pinned
/// to the REAL Rust crates here. NO fixture regeneration is needed.
///
/// The `AgentRunResume` envelope wire is asserted by CONSTRUCTION against the documented serde
/// shape/order (the merged `friday-protocol` test asserts `kind`/`signed_blob:[222,173,…]` but
/// publishes NO hex fixture), so that KAT is labeled serialization-by-construction, not
/// Rust-produced-bytes. The load-bearing facts it locks: `signed_blob` is a JSON ARRAY of byte
/// numbers (serde `Vec<u8>`, NOT base64/hex, same as `auth_proof`), and the field order matches
/// the Rust struct-variant order (`kind, run_id, signed_blob`).
final class WriteKATTests: XCTestCase {

  private func hex(_ s: String) throws -> [UInt8] { try Hex.decode(s) }
  private func utf8(_ b: [UInt8]) -> String { String(decoding: b, as: UTF8.self) }

  // MARK: WK1 — WRITE constants byte-match the Rust bin constants

  /// WK1: the Swift WRITE `SESSION_AAD` / `AUTH_CHALLENGE` bytes are byte-identical to the Rust bin
  /// `hub_agent_run_server` constants — both as the utf8 strings AND as the hex of the
  /// Rust-produced B1KAT fixture (the generator used these WRITE constants). DOMAIN-SEPARATED from
  /// the read constants (`friday:ui-read-seam:…`).
  func testWK1_writeConstantsByteIdenticalToRust() throws {
    XCTAssertEqual(utf8(writeSessionAad), "friday:execrun:ws:s-c:agent-run-session:aad:v1")
    XCTAssertEqual(utf8(writeAuthChallenge), "friday:execrun:ws:s-c:authed-run:challenge:v1")
    // The B1KAT fixture constants ARE the WRITE path's (generated by the real Rust crates).
    XCTAssertEqual(Hex.encode(writeSessionAad), B1KAT.constants.SESSION_AAD)
    XCTAssertEqual(Hex.encode(writeAuthChallenge), B1KAT.constants.AUTH_CHALLENGE)
    // And DOMAIN-SEPARATED from the read seam's AAD/challenge.
    XCTAssertNotEqual(writeSessionAad, readSessionAad)
    XCTAssertNotEqual(writeAuthChallenge, readAuthChallenge)
  }

  // MARK: WK2 — WRITE auth_aad byte-parity (the dispatch possession-proof binding)

  /// WK2: the Swift `authAad(writeSessionAad, principal, run_id)` reproduces the EXACT Rust
  /// `auth_aad` bytes — the length-delimited binding `aad || BE32(len(principal)) || principal ||
  /// BE32(len(run_id)) || run_id`. A DIRECT byte assertion against the Rust-PRODUCED `B1KAT.k3Auth.
  /// authAad` (whose `bound_context` IS `run-k3-fixture`, a run_id — exactly the WRITE path's
  /// binding). Validates that a WRITE `auth_proof` cannot be lifted to a different `(principal,
  /// run_id)`.
  func testWK2_writeAuthAadByteIdenticalToRust() throws {
    let built = FridayCrypto.authAad(writeSessionAad,
                                     forwardedPrincipal: B1KAT.k3Auth.principal,
                                     boundContext: Array(B1KAT.k3Auth.runId.utf8))
    XCTAssertEqual(Hex.encode(built), B1KAT.k3Auth.authAad,
                   "Swift write auth_aad must byte-match the Rust-produced auth_aad (run_id-bound)")
  }

  /// WK2: the Swift `nonceBoundChallenge(writeAuthChallenge, sessionNonce)` reproduces the EXACT
  /// Rust `nonce_bound_challenge` bytes for the WRITE path — the 64-byte nonce bound VERBATIM. A
  /// DIRECT byte assertion against the Rust-produced `B1KAT.k3Auth.nonceBoundChallenge` (which uses
  /// the WRITE `AUTH_CHALLENGE`).
  func testWK2_writeNonceBoundChallengeByteIdenticalToRust() throws {
    let sessionNonce = try hex(B1KAT.k3Auth.sessionNonce)
    XCTAssertEqual(sessionNonce.count, 64)
    let built = FridayCrypto.nonceBoundChallenge(writeAuthChallenge, sessionNonce: sessionNonce)
    XCTAssertEqual(Hex.encode(built), B1KAT.k3Auth.nonceBoundChallenge)
  }

  /// WK2 proof construction: `buildAuthProof` over the WRITE constants produces a blob that opens
  /// to the WRITE nonce-bound challenge under the WRITE auth AAD — proves the dispatch wires
  /// `authAad`/`nonceBoundChallenge`/`seal`/`encodeSealed` together with the WRITE constants. The
  /// TRUE Rust-accepts-the-proof check is the deferred slice-6 live e2e.
  func testWK2_writeBuildAuthProofOpensToTheNonceBoundChallenge() throws {
    let sessionKey = try hex(B1KAT.k2Aead.key)
    let sessionNonce = try hex(B1KAT.k3Auth.sessionNonce)
    let principal = B1KAT.k3Auth.principal
    let runId = "run-write-roundtrip-1"
    let proofWire = try FridayCrypto.buildAuthProof(
      sessionKey: sessionKey, sessionNonce: sessionNonce,
      sessionAad: writeSessionAad, authChallenge: writeAuthChallenge,
      forwardedPrincipal: principal, boundContext: Array(runId.utf8))
    let reqAad = FridayCrypto.authAad(writeSessionAad, forwardedPrincipal: principal, boundContext: Array(runId.utf8))
    let opened = try FridayCrypto.open(key: sessionKey, sealed: FridayCrypto.decodeSealed(proofWire), aad: reqAad)
    XCTAssertEqual(opened, FridayCrypto.nonceBoundChallenge(writeAuthChallenge, sessionNonce: sessionNonce))
  }

  /// WK2 anti-lift negative: a WRITE proof sealed for `(principalA, runA)` does NOT open under the
  /// AAD for a DIFFERENT principal or run id — the length-delimited binding is what gives the WRITE
  /// path the anti-lift guarantee (a captured dispatch proof can't be replayed onto another run).
  func testWK2_writeProofCannotBeLiftedToAnotherRun() throws {
    let sessionKey = try hex(B1KAT.k2Aead.key)
    let sessionNonce = try hex(B1KAT.k3Auth.sessionNonce)
    let principal = B1KAT.k3Auth.principal
    let proofWire = try FridayCrypto.buildAuthProof(
      sessionKey: sessionKey, sessionNonce: sessionNonce,
      sessionAad: writeSessionAad, authChallenge: writeAuthChallenge,
      forwardedPrincipal: principal, boundContext: Array("run-A".utf8))
    // A DIFFERENT run id's AAD must fail (the proof is bound to "run-A").
    let liftedRunAad = FridayCrypto.authAad(writeSessionAad, forwardedPrincipal: principal, boundContext: Array("run-B".utf8))
    XCTAssertThrowsError(try FridayCrypto.open(key: sessionKey, sealed: FridayCrypto.decodeSealed(proofWire), aad: liftedRunAad))
    // And a DIFFERENT principal's AAD.
    let liftedPrincipalAad = FridayCrypto.authAad(writeSessionAad, forwardedPrincipal: "principal:attacker", boundContext: Array("run-A".utf8))
    XCTAssertThrowsError(try FridayCrypto.open(key: sessionKey, sealed: FridayCrypto.decodeSealed(proofWire), aad: liftedPrincipalAad))
  }

  // MARK: WK3 — the constraints wire emits ONLY restrictions (the #670 INV-2/INV-7 surface proof)

  /// WK3 (the load-bearing parity KAT): even a constraints block POPULATED with a mutating grant +
  /// the operator-signed gate marker serializes to a wire object containing ONLY the three
  /// RESTRICTION fields (`read_only`/`disabled_tools`/`max_turns`). `mutatingToolGrant` /
  /// `mutationGate` are admission HINTS consumed by the TS route predicate (#670) — they NEVER
  /// reach the wire. This is the Swift-side proof that the ungated-mutation admission SURFACE on
  /// the wire is EXACTLY ZERO (#670 INV-2/INV-7): there is no wire field by which a client can
  /// GRANT a mutating capability, only ones that TIGHTEN.
  func testWK3_constraintsWireEmitsOnlyRestrictions_neverAGrant() throws {
    let constraints = AgentRunConstraintsWire(
      readOnly: false,
      disabledTools: ["run_command"],
      maxTurns: 6,
      mutatingToolGrant: ["write_file", "edit_file", "delete_file"], // admission hint — NOT a wire field
      mutationGate: "operator_signed_ed25519"                        // admission hint — NOT a wire field
    )
    let data = try JSONEncoder().encode(constraints)
    let obj = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
    // ONLY the restriction keys are present.
    XCTAssertEqual(Set(obj.keys), ["disabled_tools", "max_turns"],
                   "read_only:false is omitted; only the asserted restriction keys ride the wire")
    let json = String(decoding: data, as: UTF8.self)
    // The grant + gate markers are ABSENT from the wire — the ungated-mutation surface is ZERO.
    XCTAssertFalse(json.contains("mutating_tool_grant"))
    XCTAssertFalse(json.contains("mutatingToolGrant"))
    XCTAssertFalse(json.contains("write_file"))
    XCTAssertFalse(json.contains("edit_file"))
    XCTAssertFalse(json.contains("delete_file"))
    XCTAssertFalse(json.contains("operator_signed_ed25519"))
    XCTAssertFalse(json.contains("mutation_gate"))
    XCTAssertFalse(json.contains("mutationGate"))
  }

  /// WK3: `read_only: true` IS emitted (the only mutating-relevant field — a restriction). A
  /// read-only-OFF run never emits `read_only` (Rust `#[serde(default)]`; the TS courier never
  /// emits `read_only: false`), keeping a non-read-only request byte-clean.
  func testWK3_readOnlyEmittedOnlyWhenTrue() throws {
    let on = AgentRunConstraintsWire(readOnly: true)
    let onJson = String(decoding: try JSONEncoder().encode(on), as: UTF8.self)
    XCTAssertTrue(onJson.contains("\"read_only\":true"))

    // read_only:false + no other tightening ⇒ the whole block is wire-empty (omitted upstream).
    let off = AgentRunConstraintsWire(readOnly: false)
    XCTAssertTrue(off.isWireEmpty)
    let offJson = String(decoding: try JSONEncoder().encode(off), as: UTF8.self)
    XCTAssertFalse(offJson.contains("read_only"))
  }

  /// WK3: the disabled-tool set is normalized EXACTLY like the TS courier / Rust `RunPolicy::new`
  /// (trim, drop empties, de-dup, order-preserving) before it rides the wire — a
  /// whitespace/duplicate entry can never bloat or weaken the set.
  func testWK3_disabledToolsNormalizedLikeRustAndTs() throws {
    let c = AgentRunConstraintsWire(disabledTools: ["  run_command ", "run_command", "", "  ", "edit_file"])
    let data = try JSONEncoder().encode(c)
    let obj = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
    XCTAssertEqual(obj["disabled_tools"] as? [String], ["run_command", "edit_file"])
  }

  /// WK3: a constraints block asserting NO tightening is `isWireEmpty` ⇒ the whole `constraints`
  /// key is OMITTED from the `AgentRunRequest` (byte-identity with the pre-A1 request, exactly like
  /// the TS courier returning `undefined`).
  func testWK3_emptyConstraintsOmittedFromAgentRunRequest() throws {
    let req = AgentRunRequestWire(
      runId: "run-x", task: "t", forwardedPrincipal: "p", authProof: [1, 2, 3],
      constraints: AgentRunConstraintsWire()) // nothing asserted
    let env = FridayEnvelope(msgId: "m", sentAt: 1, message: .agentRunRequest(req))
    let json = String(decoding: try env.encodeJSON(), as: UTF8.self)
    XCTAssertFalse(json.contains("constraints"),
                   "a constraint-free AgentRunRequest must omit the constraints key (byte-identical to pre-A1)")
  }

  // MARK: WK4 — the AgentRunRequest envelope wire shape (sessionless byte-identity)

  /// WK4: a sessionless, constraint-free `AgentRunRequest` carries NEITHER `session_id` NOR
  /// `constraints` (byte-identical to the pre-A1/A2a wire), `auth_proof` is a JSON ARRAY of byte
  /// numbers (serde `Vec<u8>`), and the field order matches the Rust struct-variant order
  /// (`kind, run_id, task, forwarded_principal, auth_proof`).
  func testWK4_sessionlessAgentRunRequestWire() throws {
    let req = AgentRunRequestWire(
      runId: "run-1", task: "summarize the inbox", forwardedPrincipal: "owner-1",
      authProof: [0xDE, 0xAD, 0xBE, 0xEF])
    let env = FridayEnvelope(msgId: "m1", sentAt: 1000, message: .agentRunRequest(req))
    let json = String(decoding: try env.encodeJSON(), as: UTF8.self)
    XCTAssertTrue(json.contains("\"kind\":\"AgentRunRequest\""))
    XCTAssertFalse(json.contains("session_id"))
    XCTAssertFalse(json.contains("constraints"))
    // serde Vec<u8> ⇒ a JSON array of byte numbers (NOT base64/hex).
    XCTAssertTrue(json.contains("\"auth_proof\":[222,173,190,239]"))
    // Round-trips back to the same message.
    let back = try FridayEnvelope.decodeJSON(Data(json.utf8))
    XCTAssertEqual(back.message, .agentRunRequest(req))
  }

  /// WK4: a sessioned request carries `session_id` and round-trips it (mirrors the Rust
  /// `agent_run_request_sessioned_round_trips_with_session_id` test).
  func testWK4_sessionedAgentRunRequestCarriesSessionId() throws {
    let req = AgentRunRequestWire(
      runId: "run-2", task: "compare it", forwardedPrincipal: "owner-1",
      authProof: [1, 2], sessionId: "sess-abc")
    let env = FridayEnvelope(msgId: "m2", sentAt: 2000, message: .agentRunRequest(req))
    let json = String(decoding: try env.encodeJSON(), as: UTF8.self)
    XCTAssertTrue(json.contains("\"session_id\":\"sess-abc\""))
    XCTAssertEqual(try FridayEnvelope.decodeJSON(Data(json.utf8)).message, .agentRunRequest(req))
  }

  // MARK: WK5 — the AgentRunResume envelope wire (the S6 relay; byte-exact by construction)

  /// WK5: the `AgentRunResume` envelope wire CONTRACT — the field-NAME + value-ENCODING + tag, the
  /// part byte-parity actually requires: `kind:"AgentRunResume"`, snake_case `run_id`, and
  /// `signed_blob` a JSON ARRAY of byte numbers (serde `Vec<u8>`, NOT base64/hex — the SAME encoding
  /// as `auth_proof`). The merged `friday-protocol` test asserts `signed_blob:[222,173,190,239,0,1]`
  /// for exactly these bytes — this KAT reproduces that, plus the order-AGNOSTIC round-trip.
  ///
  /// NOT a JSON-key-ORDER match: the envelope is SEALED then serde-parsed order-independently (the
  /// MAC is over ciphertext+AAD each side computes alone — no side ever diffs the other's JSON
  /// bytes), so key order is irrelevant to parity AND Swift's `JSONEncoder` does not honor a stable
  /// order anyway. This is the SAME stance #677's `testEnvelopeRoundTrips` takes ("NOT a parity
  /// assertion — sealed then serde-parsed, order-agnostic"). INV-1: the blob rides VERBATIM.
  func testWK5_agentRunResumeEnvelopeWireContract() throws {
    let blob: [UInt8] = [0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x01]
    let env = FridayEnvelope(
      msgId: "agent-run-resume-run-9", sentAt: 4242,
      message: .agentRunResume(runId: "run-9", signedBlob: blob)
    ).withCorrelation("agent-run-resume-run-9")
    let json = String(decoding: try env.encodeJSON(), as: UTF8.self)
    XCTAssertTrue(json.contains("\"kind\":\"AgentRunResume\""))
    XCTAssertTrue(json.contains("\"run_id\":\"run-9\""))
    // serde Vec<u8> ⇒ a JSON array of byte numbers, matching the merged friday-protocol test vector.
    XCTAssertTrue(json.contains("\"signed_blob\":[222,173,190,239,0,1]"),
                  "signed_blob must be a JSON array of byte numbers (serde Vec<u8>), not base64/hex: \(json)")
    // The message carries ONLY {kind, run_id, signed_blob} — no auth_proof/forwarded_principal
    // (resume is self-authenticating via the blob's nonce; INV-1 carries no possession proof).
    let messageObj = try messageObject(json)
    XCTAssertEqual(Set(messageObj.keys), ["kind", "run_id", "signed_blob"])
    // Round-trips back to the same message (the blob is recovered VERBATIM, order-agnostic).
    let back = try FridayEnvelope.decodeJSON(Data(json.utf8))
    XCTAssertEqual(back.message, .agentRunResume(runId: "run-9", signedBlob: blob))
  }

  /// WK5: the courier relays the blob VERBATIM — an arbitrary blob round-trips byte-for-byte
  /// (INV-1: the client never mints/inspects/mutates the signing material).
  func testWK5_resumeRelaysSignedBlobVerbatim() throws {
    let blob: [UInt8] = (0..<37).map { UInt8($0 &* 7 &+ 3) }
    let env = FridayEnvelope(msgId: "x", sentAt: 1, message: .agentRunResume(runId: "run-verbatim", signedBlob: blob))
    let back = try FridayEnvelope.decodeJSON(try env.encodeJSON())
    guard case .agentRunResume(let runId, let recovered) = back.message else {
      return XCTFail("expected AgentRunResume")
    }
    XCTAssertEqual(runId, "run-verbatim")
    XCTAssertEqual(recovered, blob, "the signed blob must round-trip byte-for-byte (verbatim relay)")
  }

  // MARK: WK6 — the AgentRunPaused / AgentRunResult / AgentRunControlResult wire (refs-only)

  /// WK6: an `AgentRunPaused` frame round-trips and is REFS-ONLY — it carries the nonce +
  /// action_digest + summary, and NO signing material / body. Mirrors the Rust
  /// `AgentRunPaused` serde test's refs-only assertion.
  func testWK6_agentRunPausedRefsOnly() throws {
    let paused = AgentRunPausedWire(
      runId: "run-7", nonce: String(repeating: "a", count: 64),
      actionDigest: String(repeating: "b", count: 64), summary: "write_file")
    let env = FridayEnvelope(msgId: "m", sentAt: 1, message: .agentRunPaused(paused))
    let json = String(decoding: try env.encodeJSON(), as: UTF8.self)
    XCTAssertTrue(json.contains("\"kind\":\"AgentRunPaused\""))
    // REFS-ONLY: no signing material / private key / signature bytes leak into the pause frame.
    for forbidden in ["signed_blob", "private", "secret_key", "signature"] {
      XCTAssertFalse(json.contains(forbidden), "AgentRunPaused leaked \(forbidden): \(json)")
    }
    XCTAssertEqual(try FridayEnvelope.decodeJSON(Data(json.utf8)).message, .agentRunPaused(paused))
  }

  /// WK6: a no-answer `AgentRunResult` omits the fingerprint + count fields (refs-only,
  /// `skip_serializing_if`), and a populated one round-trips. Mirrors the Rust
  /// `agent_run_result_round_trips_over_envelope` test.
  func testWK6_agentRunResultRefsOnlyOptionalFields() throws {
    let full = AgentRunResultWire(
      runId: "run-1", status: "completed",
      answerSha256: String(repeating: "a", count: 64), answerLen: 4096, turns: 3, executedTools: 2)
    let fullEnv = FridayEnvelope(msgId: "m", sentAt: 1, message: .agentRunResult(full))
    XCTAssertEqual(try FridayEnvelope.decodeJSON(try fullEnv.encodeJSON()).message, .agentRunResult(full))

    let noAnswer = AgentRunResultWire(runId: "run-2", status: "no_answer")
    let json = String(decoding: try FridayEnvelope(msgId: "m", sentAt: 1, message: .agentRunResult(noAnswer)).encodeJSON(), as: UTF8.self)
    for omitted in ["answer_sha256", "answer_len", "turns", "executed_tools", "prompt_tokens", "completion_tokens"] {
      XCTAssertFalse(json.contains(omitted), "a no-answer result must omit \(omitted): \(json)")
    }
  }

  /// WK6: an `AgentRunControlResult` round-trips; a refused (`accepted:false`) control result with
  /// no audit ref omits the `audit_ref` key.
  func testWK6_agentRunControlResultRoundTrips() throws {
    let refused = AgentRunControlResultWire(runId: "run-1", op: "resume", accepted: false, status: "denied")
    let json = String(decoding: try FridayEnvelope(msgId: "m", sentAt: 1, message: .agentRunControlResult(refused)).encodeJSON(), as: UTF8.self)
    XCTAssertTrue(json.contains("\"accepted\":false"))
    XCTAssertFalse(json.contains("audit_ref"))

    let accepted = AgentRunControlResultWire(runId: "run-1", op: "resume", accepted: true, status: "mutation_completed", auditRef: "audit://chain/abc")
    let env = FridayEnvelope(msgId: "m", sentAt: 1, message: .agentRunControlResult(accepted))
    XCTAssertEqual(try FridayEnvelope.decodeJSON(try env.encodeJSON()).message, .agentRunControlResult(accepted))
  }

  // MARK: helpers

  /// Decode the envelope JSON and return its `message` object as a key/value map — so a KAT can
  /// assert the EXACT set of keys the message carries (order-agnostic), the wire-shape contract
  /// that parity actually requires.
  private func messageObject(_ json: String) throws -> [String: Any] {
    let env = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(json.utf8)) as? [String: Any])
    return try XCTUnwrap(env["message"] as? [String: Any], "envelope has no message object")
  }
}
