import CryptoKit
import Foundation
import FridayRustClient

// MARK: - Device keypair identity (Keychain-persisted, the real-device read-seam peer)
//
// The CLIENT half of the J2/I4 mobile read-half. A real phone has NO `~/.friday/master.key`, so the
// master-derived `MasterKeyPeer` path (the desktop/host live-read identity) yields honest
// `.masterKeyMissing` on a device. This type gives the phone its OWN device-generated X25519 keypair
// identity, persisted in the iOS Keychain, whose PUBLIC key the operator enrolls into the
// read-projection server's peer-allowlist via the already-built
// `hub_read_seam_enroll --pubkey <64-hex> --add` (the read seam is multi-peer on the hub side).
//
// CRYPTO PARITY (no divergent crypto): the secret is a 32-byte X25519 scalar generated by the SAME
// CryptoKit `Curve25519.KeyAgreement.PrivateKey()` CSPRNG that `FridayCrypto.DeviceKeypair()` uses
// internally; the public key + ECDH all flow through the shared, KAT-proven
// `FridayCrypto.DeviceKeypair(secretBytes:)` derivation. The only thing this file adds is the
// PERSISTENCE of the raw scalar (so the identity is stable across launches and the SAME pubkey can
// be enrolled once). `publicKeyHex` is therefore a 64-hex value the hub's `--pubkey` flag accepts.
//
// SECURE ENCLAVE NOTE (honest): the Secure Enclave can ONLY hold P-256 (NIST) keys — it cannot store
// or generate Curve25519/X25519. Routing through the SE would produce a P-256 key the hub's X25519
// peer-allowlist cannot enroll. So the device secret is a raw 32-byte X25519 scalar stored as a
// `kSecClassGenericPassword` Keychain item with `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`
// (device-bound, NOT iCloud-synced). That satisfies the real intent: the private scalar never leaves
// the device, is never synced, and is never logged/exported by this code.
//
// SECRET DISCIPLINE: only the PUBLIC key (`publicKeyHex`) is ever surfaced. The 32-byte secret scalar
// lives in the Keychain and in a transient local that feeds `DeviceKeypair(secretBytes:)`; it is
// NEVER printed, logged, or returned to a caller.
//
// HERMETIC TESTS: persistence sits behind the `DeviceKeypairBackend` protocol so the
// generate→persist→reload determinism test runs against an in-memory backend (the real Keychain
// requires a code-signed app / entitlement and is operator-gated on-device). This mirrors the
// codebase's own `environment:`/`homeDirectory:` injection in `MasterKeyPeer`.

/// A persisted device keypair identity for the mobile read-seam.
///
/// Wraps the shared `FridayCrypto.DeviceKeypair` (so there is NO second crypto type doing the X25519
/// work) and exposes the enrollable `publicKeyHex`. The secret scalar is held by `keypair` (whose
/// `secret` is private inside `FridayCrypto.DeviceKeypair`) — it is never re-exported from here.
///
/// NOT `Sendable` (mirrors `FridayCrypto.DeviceKeypair` + `MasterKeyPeer.deriveKeypair()`'s return,
/// which holds a non-Sendable CryptoKit `Curve25519.KeyAgreement.PrivateKey`): the keypair is built
/// at launch and handed straight to `makeLive(deviceKeypair:)` on the same actor, never shared.
public struct DeviceKeypair {
  /// The shared-crypto X25519 keypair reconstructed from the persisted secret scalar. Its
  /// `.publicKey` is the value enrolled in the server's peer-allowlist.
  public let keypair: FridayCrypto.DeviceKeypair

  /// The 64-hex (32-byte) X25519 PUBLIC key — the exact value the operator passes to
  /// `hub_read_seam_enroll --pubkey <hex> --add` when pairing this device. Lowercase hex, no `0x`.
  public var publicKeyHex: String { Hex.encode(keypair.publicKey) }

  fileprivate init(keypair: FridayCrypto.DeviceKeypair) {
    self.keypair = keypair
  }
}

/// Typed failures for the device-keypair store. The error vocabulary names a failure CATEGORY,
/// never a secret value.
public enum DeviceKeypairStoreError: Error, Equatable, CustomStringConvertible {
  /// The Keychain (or injected backend) reported an unexpected OSStatus on read/write/delete.
  case keychain(OSStatus)
  /// A stored secret was the wrong byte width (corrupt/foreign item) — fail closed, never pad.
  case storedSecretWrongLength(Int)
  /// The generated/loaded secret was not a valid X25519 scalar (constructor rejected it).
  case invalidSecret

  public var description: String {
    switch self {
    case let .keychain(status): return "device keypair keychain error (OSStatus \(status))"
    case let .storedSecretWrongLength(n): return "stored device secret must be 32 bytes, got \(n)"
    case .invalidSecret: return "stored/generated device secret is not a valid x25519 scalar"
    }
  }
}

// MARK: - Persistence backend (injectable for hermetic tests)

/// The minimal persistence contract for the device secret scalar. The default implementation is the
/// iOS Keychain; tests inject an in-memory backend so they never touch a real keychain (which on the
/// unsigned `swift test` host would fail with `errSecMissingEntitlement` / prompt / pollute the login
/// keychain). All values are the raw 32-byte X25519 secret — backends MUST NOT log them.
public protocol DeviceKeypairBackend: Sendable {
  /// Return the persisted secret bytes, or `nil` if none is stored. Throws on a backend error.
  func loadSecret() throws -> [UInt8]?
  /// Persist `secret` (overwriting any prior value). Throws on a backend error.
  func storeSecret(_ secret: [UInt8]) throws
}

/// The iOS Keychain backend: a single `kSecClassGenericPassword` item, accessible
/// `WhenUnlockedThisDeviceOnly` (device-bound, non-synced). The raw 32-byte X25519 secret scalar is
/// the item's `kSecValueData`. This is the SHIPPED backend on a real device.
public struct KeychainDeviceKeypairBackend: DeviceKeypairBackend {
  /// Default Keychain service identifier for the device read-seam identity.
  public static let defaultService = "com.friday.mobile.read-seam.device-keypair"
  /// Default account name within the service.
  public static let defaultAccount = "x25519-secret-v1"

  private let service: String
  private let account: String

  public init(
    service: String = KeychainDeviceKeypairBackend.defaultService,
    account: String = KeychainDeviceKeypairBackend.defaultAccount
  ) {
    self.service = service
    self.account = account
  }

  private var baseQuery: [String: Any] {
    [
      kSecClass as String: kSecClassGenericPassword,
      kSecAttrService as String: service,
      kSecAttrAccount as String: account,
    ]
  }

  public func loadSecret() throws -> [UInt8]? {
    var query = baseQuery
    query[kSecReturnData as String] = true
    query[kSecMatchLimit as String] = kSecMatchLimitOne
    var item: CFTypeRef?
    let status = SecItemCopyMatching(query as CFDictionary, &item)
    switch status {
    case errSecSuccess:
      guard let data = item as? Data else { return nil }
      return [UInt8](data)
    case errSecItemNotFound:
      return nil
    default:
      throw DeviceKeypairStoreError.keychain(status)
    }
  }

  public func storeSecret(_ secret: [UInt8]) throws {
    // Delete any prior item first so this is idempotent (and so a re-store with a changed
    // accessibility class takes effect). `errSecItemNotFound` on delete is fine.
    let deleteStatus = SecItemDelete(baseQuery as CFDictionary)
    guard deleteStatus == errSecSuccess || deleteStatus == errSecItemNotFound else {
      throw DeviceKeypairStoreError.keychain(deleteStatus)
    }
    var add = baseQuery
    add[kSecValueData as String] = Data(secret)
    add[kSecAttrAccessible as String] = kSecAttrAccessibleWhenUnlockedThisDeviceOnly
    let addStatus = SecItemAdd(add as CFDictionary, nil)
    guard addStatus == errSecSuccess else {
      throw DeviceKeypairStoreError.keychain(addStatus)
    }
  }
}

// MARK: - Store

/// Generates + persists the device keypair identity, idempotently.
public enum DeviceKeypairStore {
  /// Load the persisted device keypair, generating + persisting one on first use.
  ///
  /// Idempotent: the FIRST call generates a fresh 32-byte X25519 secret scalar (CryptoKit CSPRNG —
  /// the SAME source `FridayCrypto.DeviceKeypair()` uses) and persists it via `backend`; EVERY later
  /// call reloads that SAME secret, so `publicKeyHex` is stable across launches (the operator enrolls
  /// the pubkey ONCE). The returned `DeviceKeypair` reconstructs the keypair through the shared,
  /// KAT-proven `FridayCrypto.DeviceKeypair(secretBytes:)` derivation — no divergent crypto.
  ///
  /// - Parameter backend: persistence backend; defaults to the iOS Keychain. Tests inject an
  ///   in-memory backend so they never touch a real keychain.
  /// - Throws: `DeviceKeypairStoreError` on a backend error or a corrupt stored secret. Never
  ///   silently regenerates over a wrong-length item (that would change the identity and silently
  ///   invalidate a prior enrollment) — it fails closed so the operator can re-pair deliberately.
  public static func loadOrGenerate(
    backend: DeviceKeypairBackend = KeychainDeviceKeypairBackend()
  ) throws -> DeviceKeypair {
    if let existing = try backend.loadSecret() {
      guard existing.count == FridayCrypto.x25519SecretLen else {
        throw DeviceKeypairStoreError.storedSecretWrongLength(existing.count)
      }
      return try reconstruct(secret: existing)
    }
    // First use: generate a fresh X25519 scalar via the shared crypto's CSPRNG keygen, persist it,
    // then reconstruct through the shared derivation. The raw scalar (`.rawRepresentation`) is the
    // 32-byte seed CryptoKit reconstructs the same private key (and thus the same pubkey) from.
    let fresh = Curve25519.KeyAgreement.PrivateKey()
    let secret = [UInt8](fresh.rawRepresentation)
    try backend.storeSecret(secret)
    return try reconstruct(secret: secret)
  }

  private static func reconstruct(secret: [UInt8]) throws -> DeviceKeypair {
    do {
      return DeviceKeypair(keypair: try FridayCrypto.DeviceKeypair(secretBytes: secret))
    } catch {
      throw DeviceKeypairStoreError.invalidSecret
    }
  }
}
