import Foundation
import FridayRustClient

public enum MobilePairingPreflightMode: String, Sendable, Equatable {
  case empty
  case ready
  case invalid
  case expired
  case deviceKeyUnavailable
}

/// The mobile-side QR pairing preflight.
///
/// This is deliberately not an enrollment receipt: it validates the scanned QR manifest, prepares
/// the device public key, and surfaces redacted refs for UI. It never writes Hub trust state, never
/// sends the QR secret over the network, and never claims the device is connected.
public struct MobilePairingPreflight: Sendable, Equatable {
  public let mode: MobilePairingPreflightMode
  public let projection: FridayPairingManifestProjection?
  public let devicePublicKeyHex: String?
  public let proofReady: Bool
  public let reason: String
  public let nextStep: String

  public static let empty = MobilePairingPreflight(
    mode: .empty,
    projection: nil,
    devicePublicKeyHex: nil,
    proofReady: false,
    reason: "No pairing QR has been scanned.",
    nextStep: "Scan a Friday Hub pairing QR to prepare this device.")

  public static func evaluate(
    qrPayload: String,
    nowMs: Int64,
    backend: DeviceKeypairBackend = KeychainDeviceKeypairBackend()
  ) -> MobilePairingPreflight {
    let payload = qrPayload.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !payload.isEmpty else { return .empty }

    let manifest: FridayPairingManifest
    do {
      manifest = try JSONDecoder().decode(FridayPairingManifest.self, from: Data(payload.utf8))
      try manifest.validate(nowMs: nowMs)
    } catch let error as FridayPairingManifestError {
      return failure(for: error)
    } catch {
      return MobilePairingPreflight(
        mode: .invalid,
        projection: nil,
        devicePublicKeyHex: nil,
        proofReady: false,
        reason: "Pairing QR is not a valid Friday manifest.",
        nextStep: "Use a fresh QR generated by this Friday Hub.")
    }

    do {
      let device = try DeviceKeypairStore.loadOrGenerate(backend: backend)
      _ = try manifest.pairingProof(forDevicePublicKey: device.keypair.publicKey)
      return MobilePairingPreflight(
        mode: .ready,
        projection: manifest.redactedProjection,
        devicePublicKeyHex: device.publicKeyHex,
        proofReady: true,
        reason: "Pairing QR is valid and this device key is ready.",
        nextStep: "Send the proof to the Hub pairing channel; connected state requires PairAck.")
    } catch {
      return MobilePairingPreflight(
        mode: .deviceKeyUnavailable,
        projection: manifest.redactedProjection,
        devicePublicKeyHex: nil,
        proofReady: false,
        reason: "Device keypair store is unavailable.",
        nextStep: "Repair the device keypair store before pairing.")
    }
  }

  private static func failure(for error: FridayPairingManifestError) -> MobilePairingPreflight {
    switch error {
    case .expired:
      return MobilePairingPreflight(
        mode: .expired,
        projection: nil,
        devicePublicKeyHex: nil,
        proofReady: false,
        reason: "Pairing QR has expired.",
        nextStep: "Generate a fresh QR on the Friday Hub.")
    case .unsupportedKind, .badHubPublicKey, .missingWebSocketEndpoint:
      return MobilePairingPreflight(
        mode: .invalid,
        projection: nil,
        devicePublicKeyHex: nil,
        proofReady: false,
        reason: "Pairing QR cannot be trusted.",
        nextStep: "Use a fresh QR generated by this Friday Hub.")
    }
  }
}
