// ─── Validation limits ───

export const FRIDAY_MEMORY_GUARD_MAX_CONTENT_BYTES = 64 * 1024; // 64KB
export const FRIDAY_MEMORY_GUARD_MAX_METADATA_BYTES = 16 * 1024; // 16KB
export const FRIDAY_MEMORY_GUARD_MAX_TAG_COUNT = 32;
export const FRIDAY_MEMORY_GUARD_MAX_TAG_LENGTH = 64;
export const FRIDAY_MEMORY_GUARD_MAX_NAMESPACE_LENGTH = 128;
export const FRIDAY_MEMORY_GUARD_MAX_KEY_LENGTH = 128;
export const FRIDAY_MEMORY_GUARD_MAX_QUERY_CHARS = 512;
export const FRIDAY_MEMORY_GUARD_MAX_QUERY_TOKENS = 24;
export const FRIDAY_MEMORY_GUARD_MAX_QUERY_TOKEN_LENGTH = 64;

// ─── Namespace/key format ───

export const FRIDAY_MEMORY_GUARD_NAMESPACE_REGEX =
  /^[a-z0-9](?:[a-z0-9-]{0,31})(?:\.[a-z0-9](?:[a-z0-9-]{0,31}))*$/;
export const FRIDAY_MEMORY_GUARD_KEY_REGEX =
  /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
export const FRIDAY_MEMORY_GUARD_TAG_REGEX =
  /^[a-z0-9][a-z0-9._:-]{0,63}$/;

// ─── Namespace isolation ───

export const FRIDAY_MEMORY_GUARD_TENANT_PREFIX = "tenant";
export const FRIDAY_MEMORY_GUARD_USER_SEGMENT = "user";
/** Channel-level namespace isolation segment (Initiative H.3). */
export const FRIDAY_MEMORY_GUARD_CHANNEL_SEGMENT = "channel";
export const FRIDAY_MEMORY_GUARD_RESERVED_NAMESPACE_PREFIXES = ["system"] as const;

// ─── Rate limits (token bucket, compile-time constants) ───

export const FRIDAY_MEMORY_GUARD_WRITE_RATE_PER_MINUTE = 100;
export const FRIDAY_MEMORY_GUARD_SEARCH_RATE_PER_MINUTE = 200;
export const FRIDAY_MEMORY_GUARD_GLOBAL_WRITE_RATE_PER_MINUTE = 2_000;
export const FRIDAY_MEMORY_GUARD_GLOBAL_SEARCH_RATE_PER_MINUTE = 4_000;

// ─── Quotas ───

export const FRIDAY_MEMORY_GUARD_QUOTA_MAX_ITEMS_PER_NAMESPACE = 10_000;
export const FRIDAY_MEMORY_GUARD_QUOTA_MAX_BYTES_PER_NAMESPACE = 100 * 1024 * 1024; // 100MB
export const FRIDAY_MEMORY_GUARD_QUOTA_APPROACHING_RATIO = 0.90;
export const FRIDAY_MEMORY_GUARD_AUTO_PRUNE_BATCH_SIZE = 250;

// ─── Scope prefix expansion ───

export const FRIDAY_MEMORY_GUARD_SCOPE_PREFIX_MAX_NAMESPACES = 1_000;

// ─── PII policy (compile-time configurable) ───

export const FRIDAY_MEMORY_GUARD_PII_MODE = "tag" as const; // "block" | "redact" | "tag"
export const FRIDAY_MEMORY_GUARD_PII_TAG_PREFIX = "pii";
export const FRIDAY_MEMORY_GUARD_EMAIL_REGEX = /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi;
export const FRIDAY_MEMORY_GUARD_US_PHONE_REGEX = /\b(?:\+1[-.\s]?)?(?:\(?[2-9]\d{2}\)?[-.\s]?)?[2-9]\d{2}[-.\s]?\d{4}\b/g;
export const FRIDAY_MEMORY_GUARD_US_SSN_REGEX = /\b(?!000|666|9\d\d)\d{3}[- ]?(?!00)\d{2}[- ]?(?!0000)\d{4}\b/g;
export const FRIDAY_MEMORY_GUARD_CREDIT_CARD_REGEX = /\b(?:\d[ -]*?){13,19}\b/g;

// ─── Output filtering ───

export const FRIDAY_MEMORY_GUARD_MAX_SEARCH_RESULTS = 50;
export const FRIDAY_MEMORY_GUARD_MAX_RESULT_CONTENT_CHARS = 8_192;
export const FRIDAY_MEMORY_GUARD_MAX_RESULT_SNIPPET_CHARS = 512;

// ─── Error codes ───

export const FRIDAY_MEMORY_GUARD_ERROR_CODES = {
  CONTENT_TOO_LARGE: "MEMORY_GUARD_CONTENT_TOO_LARGE",
  METADATA_TOO_LARGE: "MEMORY_GUARD_METADATA_TOO_LARGE",
  TAGS_TOO_MANY: "MEMORY_GUARD_TAGS_TOO_MANY",
  TAG_TOO_LONG: "MEMORY_GUARD_TAG_TOO_LONG",
  TAG_INVALID: "MEMORY_GUARD_TAG_INVALID",
  NAMESPACE_INVALID: "MEMORY_GUARD_NAMESPACE_INVALID",
  NAMESPACE_RESERVED: "MEMORY_GUARD_NAMESPACE_RESERVED",
  KEY_INVALID: "MEMORY_GUARD_KEY_INVALID",
  QUERY_INVALID: "MEMORY_GUARD_QUERY_INVALID",
  QUERY_EMPTY: "MEMORY_GUARD_QUERY_EMPTY",
  SCOPE_VIOLATION: "MEMORY_GUARD_SCOPE_VIOLATION",
  ITEM_ACCESS_DENIED: "MEMORY_GUARD_ITEM_ACCESS_DENIED",
  RATE_LIMIT_NAMESPACE_WRITE: "MEMORY_GUARD_RATE_LIMIT_NAMESPACE_WRITE",
  RATE_LIMIT_NAMESPACE_SEARCH: "MEMORY_GUARD_RATE_LIMIT_NAMESPACE_SEARCH",
  RATE_LIMIT_GLOBAL_WRITE: "MEMORY_GUARD_RATE_LIMIT_GLOBAL_WRITE",
  RATE_LIMIT_GLOBAL_SEARCH: "MEMORY_GUARD_RATE_LIMIT_GLOBAL_SEARCH",
  QUOTA_ITEMS_EXCEEDED: "MEMORY_GUARD_QUOTA_ITEMS_EXCEEDED",
  QUOTA_BYTES_EXCEEDED: "MEMORY_GUARD_QUOTA_BYTES_EXCEEDED",
  PII_BLOCKED: "MEMORY_GUARD_PII_BLOCKED",
  INTERNAL: "MEMORY_GUARD_INTERNAL",
} as const;
