export const FRIDAY_MEMORY_FTS_TABLE = "memory_items_fts";
export const FRIDAY_MEMORY_EMBEDDINGS_TABLE = "memory_embeddings";

export const FRIDAY_MEMORY_DEFAULT_LIMIT = 20;
export const FRIDAY_MEMORY_MAX_LIMIT = 500;
export const FRIDAY_MEMORY_DEFAULT_CANDIDATE_LIMIT = 250;

export const FRIDAY_MEMORY_DEFAULT_FTS_WEIGHT = 0.45;
export const FRIDAY_MEMORY_DEFAULT_SEMANTIC_WEIGHT = 0.55;

export const FRIDAY_MEMORY_DEFAULT_SOURCE = "system";
export const FRIDAY_MEMORY_DEFAULT_TTL_SECONDS = 60 * 60 * 24 * 30; // 30d

export const FRIDAY_MEMORY_DEFAULT_EMBEDDING_MODEL = "text-embedding-3-small";

export const FRIDAY_MEMORY_ERROR_CODES = {
  NOT_FOUND: "MEMORY_NOT_FOUND",
  EMBEDDING_UNAVAILABLE: "MEMORY_EMBEDDING_UNAVAILABLE",
  EMBEDDING_UNSUPPORTED_PROVIDER: "MEMORY_EMBEDDING_UNSUPPORTED_PROVIDER",
  SEARCH_EMPTY_QUERY: "MEMORY_SEARCH_EMPTY_QUERY",
  SEARCH_INVALID_QUERY: "MEMORY_SEARCH_INVALID_QUERY",
  VALIDATION_ERROR: "MEMORY_VALIDATION_ERROR",
  INVALID_VECTOR: "MEMORY_INVALID_VECTOR",
} as const;
