export const FRIDAY_SESSION_MEMORY_EXTRACTION_MIN_BATCH_SIZE = 1;
export const FRIDAY_SESSION_MEMORY_EXTRACTION_DEFAULT_BATCH_SIZE = 24;
export const FRIDAY_SESSION_MEMORY_EXTRACTION_MAX_BATCH_SIZE = 100;
export const FRIDAY_SESSION_MEMORY_EXTRACTION_DEFAULT_MAX_BATCHES = 8;
export const FRIDAY_SESSION_MEMORY_EXTRACTION_DEFAULT_MAX_ITEMS_PER_BATCH = 10;
export const FRIDAY_SESSION_MEMORY_EXTRACTION_DEFAULT_JOB_MAX_ATTEMPTS = 3;
export const FRIDAY_SESSION_MEMORY_EXTRACTION_RETRY_BASE_DELAY_MS = 30_000;
export const FRIDAY_SESSION_MEMORY_EXTRACTION_WORKER_CLAIM_LIMIT = 10;

export const FRIDAY_SESSION_MEMORY_EXTRACTION_TAG_AUTO = "source:auto";
export const FRIDAY_SESSION_MEMORY_EXTRACTION_TAG_MANUAL = "source:manual";
export const FRIDAY_SESSION_MEMORY_EXTRACTION_TAG_PREFIX_KIND = "memory_kind";

export const FRIDAY_SESSION_MEMORY_EXTRACTION_ERROR_CODES = {
  INVALID_INPUT: "SESSION_MEMORY_EXTRACTION_INVALID_INPUT",
  SESSION_NOT_FOUND: "SESSION_MEMORY_EXTRACTION_SESSION_NOT_FOUND",
  MESSAGE_SCOPE_VIOLATION: "SESSION_MEMORY_EXTRACTION_MESSAGE_SCOPE_VIOLATION",
  PROVIDER_ERROR: "SESSION_MEMORY_EXTRACTION_PROVIDER_ERROR",
  PARSE_ERROR: "SESSION_MEMORY_EXTRACTION_PARSE_ERROR",
  QUEUE_CONFLICT: "SESSION_MEMORY_EXTRACTION_QUEUE_CONFLICT",
  JOB_NOT_FOUND: "SESSION_MEMORY_EXTRACTION_JOB_NOT_FOUND",
} as const;
