export const FRIDAY_SESSION_DEFAULT_ACCOUNT_ID = "default";
export const FRIDAY_SESSION_SUBAGENT_PREFIX = "subagent";

export const FRIDAY_SESSION_STATUS_ACTIVE = "active";
export const FRIDAY_SESSION_STATUS_IDLE = "idle";
export const FRIDAY_SESSION_STATUS_ARCHIVED = "archived";
export const FRIDAY_SESSION_STATUS_PRUNED = "pruned";

export const FRIDAY_SESSION_DEFAULT_MESSAGE_LIMIT = 50;
export const FRIDAY_SESSION_MAX_MESSAGE_LIMIT = 500;

export const FRIDAY_SESSION_IDLE_TIMEOUT_MS = 30 * 60 * 1000; // 30m
export const FRIDAY_SESSION_ARCHIVE_TIMEOUT_MS = 7 * 24 * 60 * 60 * 1000; // 7d
export const FRIDAY_SESSION_PRUNE_TIMEOUT_MS = 30 * 24 * 60 * 60 * 1000; // 30d
export const FRIDAY_SESSION_HARD_DELETE_TIMEOUT_MS = 7 * 24 * 60 * 60 * 1000; // 7d after pruned

export const FRIDAY_SESSION_KEY_SEGMENT_MAX_LENGTH = 128;
export const FRIDAY_SESSION_KEY_SEGMENT_REGEX = /^[a-z0-9][a-z0-9._-]{0,127}$/;

export const FRIDAY_SESSION_MEMORY_NAMESPACE_TENANT_SEGMENT = "tenant";
export const FRIDAY_SESSION_MEMORY_NAMESPACE_CHANNEL_SEGMENT = "channel";
export const FRIDAY_SESSION_MEMORY_NAMESPACE_USER_SEGMENT = "user";
export const FRIDAY_SESSION_MEMORY_NAMESPACE_SHARED_SEGMENT = "shared";
export const FRIDAY_SESSION_MEMORY_SOURCE_PREFIX = "session";

export const FRIDAY_SESSION_FORK_DEFAULT_CONTEXT_MESSAGE_COUNT = 20;
export const FRIDAY_SESSION_FORK_MAX_CONTEXT_MESSAGE_COUNT = 200;
export const FRIDAY_SESSION_FORK_TIMEOUT_MS = 2 * 60 * 60 * 1000; // 2h
export const FRIDAY_SESSION_FORK_DEFAULT_ARCHIVE_ON_MERGE = true;

export const FRIDAY_SESSION_ERROR_CODES = {
  INVALID_KEY: "SESSION_INVALID_KEY",
  INVALID_INPUT: "SESSION_INVALID_INPUT",
  ALREADY_EXISTS: "SESSION_ALREADY_EXISTS",
  NOT_FOUND: "SESSION_NOT_FOUND",
  INVALID_STATUS_TRANSITION: "SESSION_INVALID_STATUS_TRANSITION",
  MESSAGE_VALIDATION_ERROR: "SESSION_MESSAGE_VALIDATION_ERROR",
  MESSAGE_IDEMPOTENCY_CONFLICT: "SESSION_MESSAGE_IDEMPOTENCY_CONFLICT",
  MEMORY_NAMESPACE_UNRESOLVABLE: "SESSION_MEMORY_NAMESPACE_UNRESOLVABLE",
  PRUNE_VALIDATION_ERROR: "SESSION_PRUNE_VALIDATION_ERROR",
  FORK_PARENT_NOT_FOUND: "SESSION_FORK_PARENT_NOT_FOUND",
  FORK_POINT_NOT_FOUND: "SESSION_FORK_POINT_NOT_FOUND",
  FORK_CONFLICT: "SESSION_FORK_CONFLICT",
  FORK_MERGE_VALIDATION_ERROR: "SESSION_FORK_MERGE_VALIDATION_ERROR",
  FORK_LINEAGE_MISMATCH: "SESSION_FORK_LINEAGE_MISMATCH",
} as const;
