/**
 * Unicode-aware PII / secret DETECTION normalizer (PRIV-UNICODE-REDACTION-001).
 *
 * Additive, NON-DESTRUCTIVE de-obfuscation layer for the at-rest audit-log DETAILS sink. PII and
 * credentials can be hidden from ASCII (+ full-width) shape matchers by writing characters in a
 * COMPATIBILITY form (mathematical alphanumerics `𝗌𝗄` U+1D5CC…, fullwidth `＋４４…`, ligatures
 * `ﬁ`, circled / parenthesized / superscript forms), by writing digits in a non-ASCII decimal
 * script (Arabic-Indic `+١٤١٥…`, Extended Arabic-Indic, Devanagari, …), by splicing an invisible
 * zero-width / format code point into a token (`sk-<U+200B>…`), or by splicing an ordinary
 * COMBINING MARK into it (`123-45-6<U+0301>789`, `sk-<U+0301>…`). This module builds a DETECTION
 * COPY of a string, per CODE POINT and in a principled order:
 *   (a) NFKC COMPATIBILITY FOLDING — each code point is NFKC-normalized so a compatibility form
 *       collapses to its canonical ASCII / base equivalent (`𝗌𝗄` → `sk`, `Ａ` → `A`, `ﬁ` → `fi`,
 *       `①` → `1`, `²` → `2`, NBSP → space). NFKC is applied PER CODE POINT so a match maps back to
 *       exactly the ORIGINAL code point range (see the INDEX MAP note below);
 *   (b) COMBINING MARKS (General_Category Mn / Mc / Me — `\p{M}`) are STRIPPED, defeating the
 *       combining-mark obfuscation (`6<U+0301>` → `6`, `sk-<U+0301>` → `sk-`). Marks are stripped
 *       from the NFKC output, so a precomposed form that NFKC decomposes to base + mark keeps only
 *       the base;
 *   (c) zero-width + format + default-ignorable code points (U+200B/C/D ZW*, U+2060 WORD JOINER,
 *       U+FEFF BOM, the whole `\p{Cf}` category, variation selectors, U+034F CGJ, …) are STRIPPED;
 *   (d) every remaining Unicode decimal digit (General_Category = Nd — Arabic-Indic, Extended
 *       Arabic-Indic, Devanagari, …) is folded to its ASCII 0–9 by NUMERIC VALUE (so Luhn / SSN /
 *       area-code value gates stay correct). This runs AFTER NFKC because NFKC does NOT fold
 *       Arabic-Indic / most non-Latin Nd digits — the explicit value fold stays for those.
 * It also returns a parallel INDEX MAP from each detection-copy code unit back to its ORIGINAL
 * code-unit index. A caller runs its existing shape matchers over the detection copy, then maps
 * every match [start,end) span back to the ORIGINAL span and redacts ONLY that span.
 *
 * The stored value is NEVER the normalized form. Benign multilingual text (Arabic prose / harakat,
 * Hebrew niqqud, Devanagari matras, Vietnamese, accented Latin `café`, CJK, ZWJ emoji `👨‍👩‍👧`,
 * benign math-alphanumeric words) round-trips BYTE-IDENTICAL because only the matched ORIGINAL spans
 * are spliced — a benign string that folds to no PII / secret shape produces no match, so
 * `redactUnicodeObfuscated` returns the input verbatim. This is the single shared primitive both the
 * phone/PII residual pass and the secret-shape redactor consult; it is deliberately NOT a copied
 * sink-local regex.
 */

/**
 * Code point of the digit `0` of every General_Category = Nd decimal-digit block (each block is
 * exactly 10 consecutive code points whose numeric values are 0..9 in order — a documented Unicode
 * invariant). Generated by enumerating `\p{Nd}` and splitting each maximal contiguous run into
 * 10-aligned blocks (adjacent scripts and the 5 Mathematical-digit variants land as separate
 * blocks). Any Nd code point NOT covered here is left UNFOLDED (safe: no false negative for the
 * covered families, never a false positive), so a future script simply is not de-obfuscated until
 * added — it is never corrupted.
 */
const ND_DIGIT_ZERO_CODE_POINTS: readonly number[] = [
  0x30, 0x660, 0x6f0, 0x7c0, 0x966, 0x9e6, 0xa66, 0xae6, 0xb66, 0xbe6, 0xc66, 0xce6, 0xd66, 0xde6,
  0xe50, 0xed0, 0xf20, 0x1040, 0x1090, 0x17e0, 0x1810, 0x1946, 0x19d0, 0x1a80, 0x1a90, 0x1b50,
  0x1bb0, 0x1c40, 0x1c50, 0xa620, 0xa8d0, 0xa900, 0xa9d0, 0xa9f0, 0xaa50, 0xabf0, 0xff10, 0x104a0,
  0x10d30, 0x10d40, 0x11066, 0x110f0, 0x11136, 0x111d0, 0x112f0, 0x11450, 0x114d0, 0x11650, 0x116c0,
  0x116d0, 0x116da, 0x11730, 0x118e0, 0x11950, 0x11bf0, 0x11c50, 0x11d50, 0x11da0, 0x11f50, 0x16130,
  0x16a60, 0x16ac0, 0x16b50, 0x16d70, 0x1ccf0, 0x1d7ce, 0x1d7d8, 0x1d7e2, 0x1d7ec, 0x1d7f6, 0x1e140,
  0x1e2f0, 0x1e4f0, 0x1e5f1, 0x1e950, 0x1fbf0,
];

/** code point → decimal value 0–9 for every covered Nd digit (built once). */
const ND_DIGIT_VALUE: Map<number, number> = (() => {
  const map = new Map<number, number>();
  for (const zero of ND_DIGIT_ZERO_CODE_POINTS) {
    for (let d = 0; d < 10; d += 1) map.set(zero + d, d);
  }
  return map;
})();

/**
 * Code points removed from the DETECTION copy: the `\p{Cf}` (Format) category — every zero-width
 * space / joiner (U+200B/C/D), WORD JOINER (U+2060), BOM (U+FEFF), bidi controls, Arabic number
 * signs, … — UNION the `Default_Ignorable_Code_Point` property (variation selectors U+FE0x /
 * U+E01xx, U+034F COMBINING GRAPHEME JOINER, soft hyphen, …). The two overlap heavily but neither
 * contains the other, so the union is required to strip every obfuscation-capable invisible. Tested
 * per code point (no `/g`, so no shared `lastIndex`). Stripping is DETECTION-ONLY and never touches
 * the stored original, so an over-broad strip can only ever REVEAL a real match, never corrupt text.
 */
const STRIP_CODE_POINT_RE = /[\p{Cf}\p{Default_Ignorable_Code_Point}]/u;

/**
 * Combining marks removed from the DETECTION copy: the whole `\p{M}` (Mark) category — nonspacing
 * (Mn: combining acute U+0301, Arabic harakat, Hebrew niqqud, …), spacing-combining (Mc: Devanagari
 * matras, …), and enclosing (Me: U+20DD combining enclosing circle, …). An attacker breaks the
 * SSN / card / email / secret SHAPE by splicing a mark into a token (`123-45-6<U+0301>789`,
 * `sk-<U+0301>…`); the mark is invisible-ish yet defeats the ASCII shape regex. Stripping is
 * DETECTION-ONLY and never touches the stored original, so an over-broad strip (e.g. removing a
 * benign accent) can only ever REVEAL a real match, never corrupt stored text — benign accented /
 * diacritic prose that folds to no PII shape produces no match and survives byte-identical. Tested
 * per code point (no `/g`, so no shared `lastIndex`).
 */
const COMBINING_MARK_RE = /\p{M}/u;

export interface UnicodeDetectionCopy {
  /** Digits folded to ASCII by value; zero-width / format / default-ignorable code points stripped. */
  readonly normalized: string;
  /** True iff normalization actually changed something (a strip or a value-changing fold happened). */
  readonly changed: boolean;
  /**
   * `originalIndex[k]` = the ORIGINAL code-unit index that the normalized code unit at position `k`
   * came from, for `k` in `[0, normalized.length]`; `originalIndex[normalized.length] =
   * input.length` (sentinel). A digit fold contributes ONE normalized unit mapped to the digit's
   * original start (astral digits included). A NFKC-identity pass-through code point maps each of its
   * own code units to its own original index. A stripped code point (combining mark / Cf /
   * default-ignorable) occupies NO normalized position, so its original index is skipped — that is
   * why a stripped char inside a matched span is redacted with the span while one outside survives.
   *
   * NON-DECREASING (weakly monotonic). It is STRICTLY increasing everywhere EXCEPT inside a single
   * source code point's NFKC EXPANSION "block": when NFKC expands one source code point to SEVERAL
   * output chars (`ﬁ` → `fi`, `½` → `1⁄2`), every one of those output units maps to that ONE source
   * code point's original start, so consecutive equal entries occur ONLY within one expansion.
   * `redactUnicodeObfuscated` treats each expansion block ATOMICALLY (it rounds a matched span's end
   * UP to the enclosing block boundary before mapping to original coordinates), so a match that ends
   * mid-expansion still redacts the whole covering source code point — no partial-expansion leak and
   * no over-redaction of an adjacent benign code point.
   */
  readonly originalIndex: readonly number[];
}

/**
 * Build the detection copy + index map for `input`. Iterates by CODE POINT (so astral digits, astral
 * pass-through characters, and astral compatibility forms are handled) while tracking CODE-UNIT
 * indices (the coordinate system every JS regex `match.index` uses, `u` flag or not), so a match
 * span found on `normalized` maps back exactly.
 *
 * Per original code point, in the order (a) NFKC compatibility fold → (b) strip combining marks →
 * (c) strip Cf / default-ignorable → (d) fold Nd digits to ASCII by value:
 *   - ASCII (`cp < 0x80`) is NFKC-stable, never a mark / Cf / non-ASCII digit → passed through
 *     verbatim (one unit, mapped to its own index). This keeps a pure-ASCII input `changed=false`
 *     (fast path) and BYTE-IDENTICAL, so every existing ASCII redact/preserve decision is unchanged.
 *   - Otherwise the single code point is NFKC-normalized. If NFKC is the IDENTITY for it, the strip /
 *     fold / pass-through decision is applied to the code point itself with the EXISTING per-code-unit
 *     mapping (astral pass-through keeps its two units at `i`, `i+1` — strictly increasing).
 *   - If NFKC EXPANDS or substitutes the code point, the OUTPUT string is processed char-by-char
 *     (each output char is itself stripped if a mark / Cf, folded if an Nd digit, else kept), and
 *     EVERY surviving output code unit maps back to the ONE source code point's original start `i`.
 *     A multi-char expansion therefore forms a block of equal original indices (see `originalIndex`).
 */
export function buildUnicodeDetectionCopy(input: string): UnicodeDetectionCopy {
  let normalized = "";
  const originalIndex: number[] = [];
  let changed = false;

  // Append one surviving OUTPUT code point (drawn from a NFKC expansion of the source at `i`), mapping
  // every one of its code units back to the source start `i`. Strips marks / Cf; folds Nd digits.
  const emitExpansionCodePoint = (ocp: number, i: number): void => {
    const och = String.fromCodePoint(ocp);
    if (COMBINING_MARK_RE.test(och) || STRIP_CODE_POINT_RE.test(och)) return; // strip
    const digitValue = ND_DIGIT_VALUE.get(ocp);
    if (digitValue !== undefined) {
      normalized += String.fromCharCode(0x30 + digitValue);
      originalIndex.push(i);
      return;
    }
    normalized += och;
    for (let u = 0; u < (ocp > 0xffff ? 2 : 1); u += 1) originalIndex.push(i);
  };

  let i = 0;
  while (i < input.length) {
    const cp = input.codePointAt(i) as number;
    const unitLen = cp > 0xffff ? 2 : 1;

    // (0) ASCII fast path — NFKC-stable, never a mark / Cf / non-ASCII digit.
    if (cp < 0x80) {
      normalized += String.fromCharCode(cp);
      originalIndex.push(i);
      i += 1;
      continue;
    }

    const single = String.fromCodePoint(cp);
    const folded = single.normalize("NFKC");

    if (folded === single) {
      // NFKC identity: apply strip / fold / pass-through to the code point itself, keeping the
      // existing per-code-unit mapping so astral pass-through stays strictly increasing (i, i+1).
      if (COMBINING_MARK_RE.test(single) || STRIP_CODE_POINT_RE.test(single)) {
        changed = true; // consumes original units, contributes nothing to normalized
        i += unitLen;
        continue;
      }
      const digitValue = ND_DIGIT_VALUE.get(cp);
      if (digitValue !== undefined) {
        changed = true; // a non-ASCII Nd digit always differs from its ASCII fold
        normalized += String.fromCharCode(0x30 + digitValue);
        originalIndex.push(i);
        i += unitLen;
        continue;
      }
      normalized += single; // pass-through: map each code unit to its own original index
      for (let u = 0; u < unitLen; u += 1) originalIndex.push(i + u);
      i += unitLen;
      continue;
    }

    // NFKC changed this code point (a compatibility fold / substitution / expansion). Every surviving
    // output code unit maps back to this source code point's original start `i` (block-atomic).
    changed = true;
    for (const outChar of folded) emitExpansionCodePoint(outChar.codePointAt(0) as number, i);
    i += unitLen;
  }
  originalIndex.push(input.length); // sentinel for an end-of-string span end

  return { normalized, changed, originalIndex };
}

/** A redaction span in NORMALIZED-copy code-unit coordinates plus the placeholder to splice in. */
export interface UnicodeNormalizedSpan {
  readonly start: number;
  readonly end: number;
  readonly replacement: string;
}

/** Detects redaction spans over the normalized detection copy (e.g. a phone / secret matcher). */
export type UnicodeSpanFinder = (normalized: string) => UnicodeNormalizedSpan[];

/**
 * Run each `finder` over the DETECTION copy of `input`, map every reported span back to its ORIGINAL
 * span, and splice the placeholders into `input` NON-DESTRUCTIVELY — only matched original spans
 * change; all other bytes survive byte-identical.
 *
 * `finders` order encodes PRECEDENCE: an earlier finder's span wins an overlap (e.g. a phone finder
 * before the PII-by-value finder keeps a `+`-E.164 labelled `[PHONE]` rather than `[CREDIT_CARD]`).
 * Overlapping spans are merged into one segment (extending the end, keeping the winner's
 * placeholder) so a partial overlap can never leak the uncovered tail. Fast path: if normalization
 * changed nothing, or no finder matched, `input` is returned unchanged.
 */
export function redactUnicodeObfuscated(
  input: string,
  finders: readonly UnicodeSpanFinder[],
): string {
  const copy = buildUnicodeDetectionCopy(input);
  if (!copy.changed) return input;

  const spans: Array<{ start: number; end: number; replacement: string; priority: number }> = [];
  finders.forEach((finder, priority) => {
    for (const s of finder(copy.normalized)) {
      if (s.end <= s.start) continue;
      spans.push({ start: s.start, end: s.end, replacement: s.replacement, priority });
    }
  });
  if (spans.length === 0) return input;

  // Earliest start first; on a tie the higher-precedence (lower priority index) then the longer
  // span leads, so the merge below keeps the winning placeholder.
  spans.sort((a, b) => a.start - b.start || a.priority - b.priority || b.end - a.end);

  const segments: Array<{ start: number; end: number; replacement: string }> = [];
  for (const s of spans) {
    const last = segments[segments.length - 1];
    if (last && s.start < last.end) {
      if (s.end > last.end) last.end = s.end; // extend; keep the earlier (winning) placeholder
    } else {
      segments.push({ start: s.start, end: s.end, replacement: s.replacement });
    }
  }

  // Map each normalized segment to ORIGINAL coordinates. The START auto-rounds DOWN to its block
  // start (every output unit of one source code point's NFKC expansion shares that source's original
  // index). The END is rounded UP to the enclosing block boundary FIRST: if it lands mid-expansion
  // (`originalIndex[end] === originalIndex[end - 1]`, i.e. still inside one source code point's
  // expansion), advance it to the next block so the whole covering source code point is redacted —
  // no partial-expansion leak, and (because the next code point is a different block) no
  // over-redaction of an adjacent benign code point.
  const roundUpToBlockBoundary = (end: number): number => {
    let e = end;
    while (e < copy.normalized.length && copy.originalIndex[e] === copy.originalIndex[e - 1]) e += 1;
    return e;
  };
  const mapped = segments
    .map((seg) => ({
      start: copy.originalIndex[seg.start],
      end: copy.originalIndex[roundUpToBlockBoundary(seg.end)],
      replacement: seg.replacement,
    }))
    .sort((a, b) => a.start - b.start);

  // Re-merge in ORIGINAL coordinates: end-rounding could make two normalized segments that met
  // inside a single source code point's expansion now overlap in original space. Merge overlaps,
  // keeping the earlier (higher-precedence) placeholder, so the splice below never double-writes.
  const originalSegments: Array<{ start: number; end: number; replacement: string }> = [];
  for (const seg of mapped) {
    const last = originalSegments[originalSegments.length - 1];
    if (last && seg.start < last.end) {
      if (seg.end > last.end) last.end = seg.end; // extend; keep the earlier winning placeholder
    } else {
      originalSegments.push({ start: seg.start, end: seg.end, replacement: seg.replacement });
    }
  }

  let result = input;
  for (let k = originalSegments.length - 1; k >= 0; k -= 1) {
    const seg = originalSegments[k];
    result = result.slice(0, seg.start) + seg.replacement + result.slice(seg.end);
  }
  return result;
}
