/**
 * Unicode-aware PII / secret DETECTION normalizer (PRIV-UNICODE-REDACTION-001).
 *
 * Additive, NON-DESTRUCTIVE de-obfuscation layer for the at-rest audit-log DETAILS sink. PII and
 * credentials can be hidden from ASCII (+ full-width) shape matchers by writing digits in a
 * non-ASCII decimal script (Arabic-Indic `+١٤١٥…`, Extended Arabic-Indic, Devanagari, …) or by
 * splicing zero-width / format code points into a token (`sk-<U+200B>…`). This module builds a
 * DETECTION COPY of a string:
 *   (a) every Unicode decimal digit (General_Category = Nd — Arabic-Indic, Extended Arabic-Indic,
 *       Devanagari, full-width, …) is folded to its ASCII 0–9 by NUMERIC VALUE (so Luhn / SSN /
 *       area-code value gates stay correct), and
 *   (b) zero-width + format + default-ignorable code points (U+200B/C/D ZW*, U+2060 WORD JOINER,
 *       U+FEFF BOM, the whole `\p{Cf}` category, variation selectors, U+034F CGJ, …) are stripped.
 * It also returns a parallel INDEX MAP from each detection-copy code unit back to its ORIGINAL
 * code-unit index. A caller runs its existing shape matchers over the detection copy, then maps
 * every match [start,end) span back to the ORIGINAL span and redacts ONLY that span.
 *
 * The stored value is NEVER the normalized form. Benign multilingual text (Arabic prose with short
 * digit runs, CJK, ZWJ emoji `👨‍👩‍👧`, combining marks) round-trips BYTE-IDENTICAL because only the
 * matched original spans are spliced — a fold is 1:1 (identity for the digit's own index) and a
 * stripped code point outside every match survives, while one strictly INSIDE a match span is
 * redacted with the span. This is the single shared primitive both the phone/PII residual pass and
 * the secret-shape redactor consult; it is deliberately NOT a copied sink-local regex.
 */

/**
 * Code point of the digit `0` of every General_Category = Nd decimal-digit block (each block is
 * exactly 10 consecutive code points whose numeric values are 0..9 in order — a documented Unicode
 * invariant). Generated by enumerating `\p{Nd}` and splitting each maximal contiguous run into
 * 10-aligned blocks (adjacent scripts and the 5 Mathematical-digit variants land as separate
 * blocks). Any Nd code point NOT covered here is left UNFOLDED (safe: no false negative for the
 * covered families, never a false positive), so a future script simply is not de-obfuscated until
 * added — it is never corrupted.
 */
const ND_DIGIT_ZERO_CODE_POINTS: readonly number[] = [
  0x30, 0x660, 0x6f0, 0x7c0, 0x966, 0x9e6, 0xa66, 0xae6, 0xb66, 0xbe6, 0xc66, 0xce6, 0xd66, 0xde6,
  0xe50, 0xed0, 0xf20, 0x1040, 0x1090, 0x17e0, 0x1810, 0x1946, 0x19d0, 0x1a80, 0x1a90, 0x1b50,
  0x1bb0, 0x1c40, 0x1c50, 0xa620, 0xa8d0, 0xa900, 0xa9d0, 0xa9f0, 0xaa50, 0xabf0, 0xff10, 0x104a0,
  0x10d30, 0x10d40, 0x11066, 0x110f0, 0x11136, 0x111d0, 0x112f0, 0x11450, 0x114d0, 0x11650, 0x116c0,
  0x116d0, 0x116da, 0x11730, 0x118e0, 0x11950, 0x11bf0, 0x11c50, 0x11d50, 0x11da0, 0x11f50, 0x16130,
  0x16a60, 0x16ac0, 0x16b50, 0x16d70, 0x1ccf0, 0x1d7ce, 0x1d7d8, 0x1d7e2, 0x1d7ec, 0x1d7f6, 0x1e140,
  0x1e2f0, 0x1e4f0, 0x1e5f1, 0x1e950, 0x1fbf0,
];

/** code point → decimal value 0–9 for every covered Nd digit (built once). */
const ND_DIGIT_VALUE: Map<number, number> = (() => {
  const map = new Map<number, number>();
  for (const zero of ND_DIGIT_ZERO_CODE_POINTS) {
    for (let d = 0; d < 10; d += 1) map.set(zero + d, d);
  }
  return map;
})();

/**
 * Code points removed from the DETECTION copy: the `\p{Cf}` (Format) category — every zero-width
 * space / joiner (U+200B/C/D), WORD JOINER (U+2060), BOM (U+FEFF), bidi controls, Arabic number
 * signs, … — UNION the `Default_Ignorable_Code_Point` property (variation selectors U+FE0x /
 * U+E01xx, U+034F COMBINING GRAPHEME JOINER, soft hyphen, …). The two overlap heavily but neither
 * contains the other, so the union is required to strip every obfuscation-capable invisible. Tested
 * per code point (no `/g`, so no shared `lastIndex`). Stripping is DETECTION-ONLY and never touches
 * the stored original, so an over-broad strip can only ever REVEAL a real match, never corrupt text.
 */
const STRIP_CODE_POINT_RE = /[\p{Cf}\p{Default_Ignorable_Code_Point}]/u;

export interface UnicodeDetectionCopy {
  /** Digits folded to ASCII by value; zero-width / format / default-ignorable code points stripped. */
  readonly normalized: string;
  /** True iff normalization actually changed something (a strip or a value-changing fold happened). */
  readonly changed: boolean;
  /**
   * `originalIndex[k]` = the ORIGINAL code-unit index that the normalized code unit at position `k`
   * came from, for `k` in `[0, normalized.length]`; `originalIndex[normalized.length] =
   * input.length` (sentinel). A fold contributes ONE normalized unit mapped to the digit's original
   * start (astral digits included). A pass-through code unit maps to its own original index. A
   * stripped code point occupies NO normalized position, so its original index is skipped — that is
   * why a stripped char inside a matched span is redacted with the span while one outside survives.
   * Monotonically strictly increasing, so non-overlapping normalized spans map to non-overlapping
   * original spans.
   */
  readonly originalIndex: readonly number[];
}

/**
 * Build the detection copy + index map for `input`. Iterates by CODE POINT (so astral digits and
 * astral pass-through characters are handled) while tracking CODE-UNIT indices (the coordinate
 * system every JS regex `match.index` uses, `u` flag or not), so a match span found on `normalized`
 * maps back exactly.
 */
export function buildUnicodeDetectionCopy(input: string): UnicodeDetectionCopy {
  let normalized = "";
  const originalIndex: number[] = [];
  let changed = false;

  let i = 0;
  while (i < input.length) {
    const cp = input.codePointAt(i) as number;
    const unitLen = cp > 0xffff ? 2 : 1;
    const ch = String.fromCodePoint(cp);

    if (STRIP_CODE_POINT_RE.test(ch)) {
      changed = true; // consumes original units, contributes nothing to normalized
      i += unitLen;
      continue;
    }

    const digitValue = ND_DIGIT_VALUE.get(cp);
    if (digitValue !== undefined) {
      const ascii = String.fromCharCode(0x30 + digitValue);
      if (ascii !== ch) changed = true; // ASCII digits fold to themselves — no change flag
      normalized += ascii;
      originalIndex.push(i);
      i += unitLen;
      continue;
    }

    // Pass-through: keep the code point verbatim; map each of its code units to its original index.
    normalized += ch;
    for (let u = 0; u < unitLen; u += 1) originalIndex.push(i + u);
    i += unitLen;
  }
  originalIndex.push(input.length); // sentinel for an end-of-string span end

  return { normalized, changed, originalIndex };
}

/** A redaction span in NORMALIZED-copy code-unit coordinates plus the placeholder to splice in. */
export interface UnicodeNormalizedSpan {
  readonly start: number;
  readonly end: number;
  readonly replacement: string;
}

/** Detects redaction spans over the normalized detection copy (e.g. a phone / secret matcher). */
export type UnicodeSpanFinder = (normalized: string) => UnicodeNormalizedSpan[];

/**
 * Run each `finder` over the DETECTION copy of `input`, map every reported span back to its ORIGINAL
 * span, and splice the placeholders into `input` NON-DESTRUCTIVELY — only matched original spans
 * change; all other bytes survive byte-identical.
 *
 * `finders` order encodes PRECEDENCE: an earlier finder's span wins an overlap (e.g. a phone finder
 * before the PII-by-value finder keeps a `+`-E.164 labelled `[PHONE]` rather than `[CREDIT_CARD]`).
 * Overlapping spans are merged into one segment (extending the end, keeping the winner's
 * placeholder) so a partial overlap can never leak the uncovered tail. Fast path: if normalization
 * changed nothing, or no finder matched, `input` is returned unchanged.
 */
export function redactUnicodeObfuscated(
  input: string,
  finders: readonly UnicodeSpanFinder[],
): string {
  const copy = buildUnicodeDetectionCopy(input);
  if (!copy.changed) return input;

  const spans: Array<{ start: number; end: number; replacement: string; priority: number }> = [];
  finders.forEach((finder, priority) => {
    for (const s of finder(copy.normalized)) {
      if (s.end <= s.start) continue;
      spans.push({ start: s.start, end: s.end, replacement: s.replacement, priority });
    }
  });
  if (spans.length === 0) return input;

  // Earliest start first; on a tie the higher-precedence (lower priority index) then the longer
  // span leads, so the merge below keeps the winning placeholder.
  spans.sort((a, b) => a.start - b.start || a.priority - b.priority || b.end - a.end);

  const segments: Array<{ start: number; end: number; replacement: string }> = [];
  for (const s of spans) {
    const last = segments[segments.length - 1];
    if (last && s.start < last.end) {
      if (s.end > last.end) last.end = s.end; // extend; keep the earlier (winning) placeholder
    } else {
      segments.push({ start: s.start, end: s.end, replacement: s.replacement });
    }
  }

  // Map each normalized segment to ORIGINAL coordinates and splice end-to-start (index-stable).
  const originalSegments = segments
    .map((seg) => ({
      start: copy.originalIndex[seg.start],
      end: copy.originalIndex[seg.end],
      replacement: seg.replacement,
    }))
    .sort((a, b) => a.start - b.start);

  let result = input;
  for (let k = originalSegments.length - 1; k >= 0; k -= 1) {
    const seg = originalSegments[k];
    result = result.slice(0, seg.start) + seg.replacement + result.slice(seg.end);
  }
  return result;
}
