import { describe, it, expect, beforeEach, afterEach } from "vitest";
import type { FridaySqliteLayer } from "#state";
import type { FridaySatelliteRegistrationInput } from "#satellites";
import { createFridaySatelliteRepository } from "#satellites";
import { createFridaySatellitePairingRequestRepository } from "#satellites";
import { createFridaySatelliteCapabilityRepository } from "#satellites";
import { createFridaySatelliteRegistrationService } from "#satellites";
import { createTestDb, createTestIdGenerator } from "../_helpers/create-test-db.helper.js";

describe("FridaySatelliteRegistrationService", () => {
  let db: FridaySqliteLayer;

  const NOW = "2025-01-15T10:00:00.000Z";

  const baseInput: FridaySatelliteRegistrationInput = {
    type: "phone",
    displayName: "My Phone",
    publicKey: "pk-abc123",
    runtime: {
      platform: "darwin",
      arch: "arm64",
      appVersion: "1.0.0",
      nodeVersion: "22.0.0",
    },
    transport: "ws",
  };

  beforeEach(() => {
    db = createTestDb();
  });

  afterEach(() => {
    db.close();
  });

  function createService() {
    return createFridaySatelliteRegistrationService({
      db,
      satelliteRepo: createFridaySatelliteRepository(),
      pairingRequestRepo: createFridaySatellitePairingRequestRepository(),
      capabilityRepo: createFridaySatelliteCapabilityRepository(),
      idGenerator: createTestIdGenerator(),
      nowIso: () => NOW,
    });
  }

  it("creates satellite with pending status and pairing request", () => {
    const service = createService();
    const result = service.register(baseInput);

    expect(result.pairingStatus).toBe("pending");
    expect(result.pairingRequired).toBe(true);
    expect(result.satelliteId).toBeTruthy();
    expect(result.pairingRequestId).toBeTruthy();
    expect(result.pairingCode).toMatch(/^\d{6}$/);
    expect(result.challengeNonce).toBeTruthy();
    expect(result.expiresAt).toBeTruthy();

    // Verify DB row
    const satRow = db.writer
      .prepare("SELECT * FROM satellites WHERE id = ?")
      .get(result.satelliteId) as Record<string, unknown>;
    expect(satRow.pairing_status).toBe("pending");
    expect(satRow.trust_level).toBe("restricted");
    expect(satRow.type).toBe("phone");

    // Verify pairing request row
    const reqRow = db.writer
      .prepare("SELECT * FROM satellite_pairing_requests WHERE id = ?")
      .get(result.pairingRequestId) as Record<string, unknown>;
    expect(reqRow.status).toBe("pending");
    expect(reqRow.satellite_id).toBe(result.satelliteId);
  });

  it("stores initial capabilities when provided", () => {
    const service = createService();
    const result = service.register({
      ...baseInput,
      capabilityReport: {
        satelliteId: "ignored", // satelliteId is generated by service
        revision: 1,
        generatedAt: NOW,
        runtime: { os: "darwin", arch: "arm64", appVersion: "1.0.0", nodeVersion: "22.0.0" },
        capabilities: [
          { key: "camera", available: true, metadata: { resolution: "1080p" } },
          { key: "microphone", available: false },
        ],
      },
    });

    const caps = db.writer
      .prepare("SELECT * FROM satellite_capabilities WHERE satellite_id = ? ORDER BY key")
      .all(result.satelliteId) as Array<Record<string, unknown>>;
    expect(caps).toHaveLength(2);
    expect(caps[0]!.key).toBe("camera");
    expect(caps[0]!.available).toBe(1);
    expect(caps[1]!.key).toBe("microphone");
    expect(caps[1]!.available).toBe(0);
  });

  it("generates expiry from TTL", () => {
    const service = createFridaySatelliteRegistrationService({
      db,
      satelliteRepo: createFridaySatelliteRepository(),
      pairingRequestRepo: createFridaySatellitePairingRequestRepository(),
      capabilityRepo: createFridaySatelliteCapabilityRepository(),
      idGenerator: createTestIdGenerator(),
      nowIso: () => NOW,
      pairingTtlMs: 5 * 60 * 1000, // 5 minutes
    });

    const result = service.register(baseInput);
    const expiryMs = new Date(result.expiresAt).getTime() - new Date(NOW).getTime();
    expect(expiryMs).toBe(5 * 60 * 1000);
  });
});
