import { describe, expect, it } from "vitest";

import {
  agree,
  authAad,
  buildAuthProof,
  decodeSealed,
  deviceKeypairFromSecret,
  encodeSealed,
  nonceBoundChallenge,
  open,
  seal,
} from "../../../../src/api/mission-spine/friday-rust-hub-agent-run-ws-sealed-crypto.js";
import { B1_KAT } from "./fixtures/b1-rust-handshake-kat.js";

/**
 * B1 — CI-safe KNOWN-ANSWER TESTS for the TS client-half of the friday-crypto sealed WS
 * handshake. The fixtures in `fixtures/b1-rust-handshake-kat.ts` were generated by a
 * THROWAWAY external Rust project (`b1-kat-gen`, outside the worktree) that path-deps the
 * rust-core crates and calls ONLY the real `pub` friday-crypto / friday-hub API — so they
 * anchor on the real Rust crates, NOT a reimplementation, and rust-core is byte-untouched.
 *
 * A TS-seals-then-TS-opens roundtrip would be CIRCULAR (it proves nothing about Rust
 * interop). These KATs instead make TS REPRODUCE Rust-produced bytes / OPEN Rust-produced
 * seals:
 *   - K1: TS `agree()` derives the SAME session key as Rust `DeviceKeypair::agree` — proven
 *     by OPENING a blob Rust sealed under the agreed key (a wrong TS key fails the Poly1305
 *     tag; there is no way the keys differ yet `open` succeeds). Validates X25519 + HKDF.
 *   - K2: TS `decodeSealed` + `open` recovers the plaintext from a blob Rust sealed under a
 *     KNOWN key + KNOWN AAD. Validates the AEAD + on-wire framing under a controlled key.
 *   - K3: TS `authAad` / `nonceBoundChallenge` reproduce the exact Rust `auth_aad` /
 *     `nonce_bound_challenge` bytes. Validates the per-request auth bindings.
 *
 * NOTE on K1 provenance (deliberate, justified deviation from the spec's literal phrasing):
 * the spec names K1 as "expected 32B session_key (Rust-computed) → assert TS reproduces it".
 * `friday-crypto::DataKey` deliberately exposes NO raw bytes (no Debug, no accessor), so
 * emitting the literal raw key would require either a production rust-core edit (the hard
 * STOP) or reimplementing the derivation (weaker provenance — it would prove TS matches a
 * reimpl, not the real crate). Opening a real Rust seal under the agreed key meets the stated
 * goal ("assert TS reproduces it") with STRICTLY STRONGER provenance.
 */

const KAT = B1_KAT;

const hex = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, "hex"));
const utf8 = (b: Uint8Array): string => Buffer.from(b).toString("utf8");

describe("B1 sealed-crypto — Rust-anchored KATs", () => {
  it("K1 pubkey: TS deviceKeypairFromSecret derives the SAME pubkey as Rust DeviceKeypair", () => {
    // Deterministic cross-check: the pubkey TS derives from the fixed secret must byte-match the
    // Rust-derived pubkey in the fixture (proves the X25519 secret→public derivation interops).
    const client = deviceKeypairFromSecret(hex(KAT.k1Agree.clientSecret));
    expect(Buffer.from(client.publicKey).toString("hex")).toBe(KAT.k1Agree.clientPub);
  });

  it("K1: TS agree() derives the same session key as Rust (opens a Rust-sealed blob under the agreed key)", () => {
    const client = deviceKeypairFromSecret(hex(KAT.k1Agree.clientSecret));
    const sessionKey = agree(client.secret, hex(KAT.k1Agree.serverPub));
    expect(sessionKey.length).toBe(32);

    const sealed = decodeSealed(hex(KAT.k1Agree.sealedWire));
    const opened = open(sessionKey, sealed, hex(KAT.k1Agree.aad));
    // If the TS-derived key did NOT byte-match the Rust-derived key, the Poly1305 tag would
    // fail and open() would throw — so a successful open IS the key-equality proof.
    expect(utf8(opened)).toBe(utf8(hex(KAT.k1Agree.plaintext)));
    expect(utf8(opened)).toBe("K1-AGREE-SENTINEL");
  });

  it("K1 negative: a wrong server pubkey yields a different key that cannot open the Rust blob", () => {
    const client = deviceKeypairFromSecret(hex(KAT.k1Agree.clientSecret));
    const wrongServerPub = hex(KAT.k1Agree.serverPub);
    wrongServerPub[0] ^= 0x01; // perturb one byte of the server pubkey
    const wrongKey = agree(client.secret, wrongServerPub);
    const sealed = decodeSealed(hex(KAT.k1Agree.sealedWire));
    expect(() => open(wrongKey, sealed, hex(KAT.k1Agree.aad))).toThrow();
  });

  it("K2: TS decodeSealed + open recovers a Rust seal under a known key + known AAD", () => {
    const sealed = decodeSealed(hex(KAT.k2Aead.sealedWire));
    // The on-wire framing must decode: first byte is the 24-byte nonce length.
    expect(sealed.nonce.length).toBe(24);
    const opened = open(hex(KAT.k2Aead.key), sealed, hex(KAT.k2Aead.aad));
    expect(utf8(opened)).toBe("K2-AEAD-FRAMING-SENTINEL");
  });

  it("K2 negative: a tampered AAD makes the Rust seal fail to open (AEAD binding)", () => {
    const sealed = decodeSealed(hex(KAT.k2Aead.sealedWire));
    const wrongAad = hex(KAT.k2Aead.aad);
    wrongAad[0] ^= 0x01;
    expect(() => open(hex(KAT.k2Aead.key), sealed, wrongAad)).toThrow();
  });

  it("K2 roundtrip: a TS seal under the known key opens back (encode/decode symmetry)", () => {
    const key = hex(KAT.k2Aead.key);
    const pt = hex(KAT.k2Aead.plaintext);
    const aad = hex(KAT.k2Aead.aad);
    const wire = encodeSealed(seal(key, pt, aad));
    expect(utf8(open(key, decodeSealed(wire), aad))).toBe("K2-AEAD-FRAMING-SENTINEL");
  });

  it("K3: TS authAad reproduces the exact Rust auth_aad bytes (length-delimited binding)", () => {
    const sessionAad = hex(KAT.constants.SESSION_AAD);
    const built = authAad(sessionAad, KAT.k3Auth.principal, KAT.k3Auth.runId);
    expect(Buffer.from(built).toString("hex")).toBe(KAT.k3Auth.authAad);
  });

  it("K3: TS nonceBoundChallenge reproduces the exact Rust nonce_bound_challenge bytes", () => {
    const authChallenge = hex(KAT.constants.AUTH_CHALLENGE);
    const sessionNonce = hex(KAT.k3Auth.sessionNonce);
    // The 64-byte session nonce is used VERBATIM (NOT hex-decoded to 32 bytes).
    expect(sessionNonce.length).toBe(64);
    const built = nonceBoundChallenge(authChallenge, sessionNonce);
    expect(Buffer.from(built).toString("hex")).toBe(KAT.k3Auth.nonceBoundChallenge);
  });

  it("K3: buildAuthProof produces a blob that opens to the nonce-bound challenge under the auth AAD", () => {
    // Self-consistency of the proof construction: seal the challenge under a known key with
    // the auth AAD, then open it back. (The TRUE Rust-accepts-the-proof check is the e2e
    // interop test; this asserts buildAuthProof wires authAad/nonceBoundChallenge correctly.)
    const sessionKey = hex(KAT.k2Aead.key);
    const sessionAad = hex(KAT.constants.SESSION_AAD);
    const authChallenge = hex(KAT.constants.AUTH_CHALLENGE);
    const sessionNonce = hex(KAT.k3Auth.sessionNonce);
    const proofWire = buildAuthProof({
      sessionKey,
      sessionNonce,
      sessionAad,
      authChallenge,
      forwardedPrincipal: KAT.k3Auth.principal,
      runId: KAT.k3Auth.runId,
    });
    const reqAad = authAad(sessionAad, KAT.k3Auth.principal, KAT.k3Auth.runId);
    const opened = open(sessionKey, decodeSealed(proofWire), reqAad);
    const expectedChallenge = nonceBoundChallenge(authChallenge, sessionNonce);
    expect(Buffer.from(opened).toString("hex")).toBe(Buffer.from(expectedChallenge).toString("hex"));
  });
});
