import Foundation
import Testing

@testable import FridayMobileShellCore
@testable import FridayRustClient

// MARK: - Master-derived peer-key parity KAT (offline, CI-safe)
//
// PORTED from the desktop `FridayHubConsoleCoreTests/MasterKeyPeerTests.swift` (#686). The single
// load-bearing crypto claim of the iOS live read seam: the mobile shell's master-derived X25519
// pubkey EQUALS the value the Rust enroll CLI wrote into the server's peer-allowlist (the SAME peer
// the desktop derives). If this diverges, the live handshake is refused at the allowlist (opaquely).
// These assertions pin the WHOLE chain (master → SHA256(purpose‖master) → X25519 pubkey) to the
// Rust `key_source` cross-language KAT vector — OFFLINE, deterministic, no live server, runs in CI.

/// The Rust `key_source` KAT master key (all 0x42), as the 64-hex `FRIDAY_MASTER_KEY` carries.
private let katMasterHex =
  "4242424242424242424242424242424242424242424242424242424242424242"

/// `secret = sha256("friday.rust.agent_run.ws.x25519_secret.v1" ‖ 0x42×32)` — the Rust KAT.
private let katSecretHex =
  "84a7b3761b283c9adc27b8a169f83c7ea795852a8bdbb0fa1311ca24dac0613d" // pragma: allowlist secret (public Rust key_source KAT vector, not a secret)

/// `pubkey = X25519-public(secret)` — the value the enroll CLI registered, the Rust KAT vector.
private let katPubkeyHex =
  "1d4a03c1c3af1a4639b616951c9b0e1cd1c957c9b0f25fe7a99b85101598de56" // pragma: allowlist secret (public Rust key_source KAT vector, not a secret)

@Test
func masterDerivedSecretScalarMatchesRustKat() {
  // SHA256(purpose ‖ master) must byte-match Rust `key_source::derive_client_x25519_secret`.
  let master = try! Hex.decode(katMasterHex)
  let secret = MasterKeyPeer.deriveSecretScalar(master: master)
  #expect(Hex.encode(secret) == katSecretHex)
}

@Test
func masterDerivedPubkeyMatchesRustKat() throws {
  // The full chain via the PUBLIC `deriveKeypair` (env source), reading FRIDAY_MASTER_KEY. The
  // derived pubkey must equal the enrolled allowlist peer (the Rust `key_source` KAT vector) —
  // and equal the value the desktop derives, so iOS is the SAME enrolled peer.
  let keypair = try MasterKeyPeer.deriveKeypair(
    environment: ["FRIDAY_MASTER_KEY": katMasterHex],
    homeDirectory: URL(fileURLWithPath: "/nonexistent"))  // env wins; home is never read.
  #expect(Hex.encode(keypair.publicKey) == katPubkeyHex)
}

@Test
func masterKeyMissingFailsClosedNotAutoGenerated() {
  // No env, and a home with no ~/.friday/master.key ⇒ fail closed (never auto-generate a key).
  let emptyHome = URL(fileURLWithPath: NSTemporaryDirectory())
    .appendingPathComponent("friday-no-master-\(UUID().uuidString)")
  try? FileManager.default.createDirectory(at: emptyHome, withIntermediateDirectories: true)
  #expect(throws: MasterKeyPeerError.self) {
    _ = try MasterKeyPeer.deriveKeypair(environment: [:], homeDirectory: emptyHome)
  }
}

@Test
func masterKeyWrongLengthFailsClosed() {
  // A hex master key of the wrong byte width is rejected (no truncate/pad to 32).
  #expect(throws: MasterKeyPeerError.self) {
    _ = try MasterKeyPeer.deriveKeypair(
      environment: ["FRIDAY_MASTER_KEY": "4242"],
      homeDirectory: URL(fileURLWithPath: "/nonexistent"))
  }
}

@Test
func masterKeyNonHexFailsClosed() {
  #expect(throws: MasterKeyPeerError.self) {
    _ = try MasterKeyPeer.deriveKeypair(
      environment: ["FRIDAY_MASTER_KEY": "not-hex-at-all-zz"],
      homeDirectory: URL(fileURLWithPath: "/nonexistent"))
  }
}

@Test
func masterKeyReadFromFileMatchesEnv() throws {
  // The file source (UTF-8 → trim → hex) yields the SAME keypair as the env source, including a
  // trailing newline being trimmed (how `~/.friday/master.key` is typically written).
  let home = URL(fileURLWithPath: NSTemporaryDirectory())
    .appendingPathComponent("friday-master-file-\(UUID().uuidString)")
  let dotFriday = home.appendingPathComponent(".friday")
  try FileManager.default.createDirectory(at: dotFriday, withIntermediateDirectories: true)
  try (katMasterHex + "\n").write(
    to: dotFriday.appendingPathComponent("master.key"), atomically: true, encoding: .utf8)

  let fromFile = try MasterKeyPeer.deriveKeypair(environment: [:], homeDirectory: home)
  #expect(Hex.encode(fromFile.publicKey) == katPubkeyHex)
}
