import type { FridaySqliteMigration } from "./friday-migration.types.js";
import { V001_INITIAL_MIGRATION } from "./v001-initial.js";
import { V002_PHASE8_API_FOUNDATION_MIGRATION } from "./v002-phase8-api-foundation.js";
import { V003_PROVIDER_USAGE_COST_ROUTING_MIGRATION } from "./v003-provider-usage-cost-routing.js";
import { V004_MEMORY_CORE_MIGRATION } from "./v004-memory-core.js";
import { V005_SESSION_FOUNDATION_MIGRATION } from "./v005-session-foundation.js";
import { V006_SESSION_MEMORY_EXTRACTION_MIGRATION } from "./v006-session-memory-extraction.js";
import { V007_SESSION_FORKS_MIGRATION } from "./v007-session-forks.js";
import { V008_PLUGIN_SYSTEM_FOUNDATION_MIGRATION } from "./v008-plugin-system-foundation.js";
import { V009_WORKFLOW_ENGINE_TRIGGERS_APPROVALS_MIGRATION } from "./v009-workflow-engine-triggers-approvals.js";
import { V010_PROVIDER_OAUTH_CREDENTIALS_MIGRATION } from "./v010-provider-oauth-credentials.js";
import { V011_ACCESS_TOKEN_REVOCATION_MIGRATION } from "./v011-access-token-revocation.js";
import { V012_AGENT_RUNTIME_MIGRATION } from "./v012-agent-runtime.js";
import { V013_SUBAGENT_RUNS_MIGRATION } from "./v013-subagent-runs.js";
import { V014_SETUP_WIZARD_MIGRATION } from "./v014-setup-wizard.js";
import { V015_XHS_SESSIONS_MIGRATION } from "./v015-xhs-sessions.js";
import { V016_XHS_COOKIE_ENCRYPTION_MIGRATION } from "./v016-xhs-cookie-encryption.js";
import { V017_AGENT_RUN_PLAN_REVIEW_MIGRATION } from "./v017-agent-run-plan-review.js";
import { V018_AGENT_RUN_ACTUAL_EXECUTION_MIGRATION } from "./v018-agent-run-actual-execution.js";
import { V019_AGENT_RUN_EVENTS_MIGRATION } from "./v019-agent-run-events.js";
import { V020_AGENT_RUN_CONSTRAINTS_MIGRATION } from "./v020-agent-run-constraints.js";
import { V021_AGENT_RUN_RESPONSE_TEXT_SUMMARY_MIGRATION } from "./v021-agent-run-response-text-summary.js";
import { V022_AGENT_RUN_ARTIFACT_DIR_MIGRATION } from "./v022-agent-run-artifact-dir.js";
import { V023_MEMORY_FILE_SYNC_MIGRATION } from "./v023-memory-file-sync.js";
import { V024_UNIFIED_JOB_SCHEDULER_MIGRATION } from "./v024-unified-job-scheduler.js";
import { V025_MEMORY_FILE_SYNC_TRIGGER_FIXES_MIGRATION } from "./v025-memory-file-sync-trigger-fixes.js";
import { V026_MEMORY_FILE_SYNC_EXTERNAL_MIGRATION } from "./v026-memory-file-sync-external.js";
import { V027_JOB_SCHEDULER_MULTI_SCHEDULE_MIGRATION } from "./v027-job-scheduler-multi-schedule.js";
import { V028_SUBAGENT_LIFECYCLE_SESSION_SEND_POLICY_MIGRATION } from "./v028-subagent-lifecycle-session-send-policy.js";
import { V029_HEARTBEAT_RUNNER_STATE_MIGRATION } from "./v029-heartbeat-runner-state.js";
import { V030_AGENT_AUTOMATION_SCHEDULE_LINK_MIGRATION } from "./v030-agent-automation-schedule-link.js";
import { V031_RULES_PERSISTENCE_MIGRATION } from "./v031-rules-persistence.js";
import { V032_PLAYBOOK_PERSISTENCE_MIGRATION } from "./v032-playbook-persistence.js";
import { V033_WORKFLOW_RUN_EVIDENCE_PERSISTENCE_MIGRATION } from "./v033-workflow-run-evidence-persistence.js";
import { V034_RULES_SCHEMA_BRIDGE_MIGRATION } from "./v034-rules-schema-bridge.js";
import { V035_AUTH_TOKEN_INDEXES_MIGRATION } from "./v035-auth-token-indexes.js";
import { V036_WORKFLOW_INDEXES_MIGRATION } from "./v036-workflow-indexes.js";
import { V037_FK_AND_PLAYBOOK_INDEX_MIGRATION } from "./v037-fk-and-playbook-index.js";
import { V038_RETIRED_FEATURE_RESERVED_A_MIGRATION } from "./v038-retired-feature-reserved-a.js";
import { V039_RETIRED_FEATURE_RESERVED_B_MIGRATION } from "./v039-retired-feature-reserved-b.js";
import { V040_SETUP_STATE_REVISION_MIGRATION } from "./v040-setup-state-revision.js";
import { V041_CHANNEL_AGENT_BINDINGS_MIGRATION } from "./v041-channel-agent-bindings.js";
import { V042_RETIRED_FEATURE_RESERVED_C_MIGRATION } from "./v042-retired-feature-reserved-c.js";
import { V043_SYSTEM_AGENT_OS_LAYER_MIGRATION } from "./v043-system-agent-os-layer.js";
import { V044_SYSTEM_REMOTE_SESSIONS_MIGRATION } from "./v044-system-remote-sessions.js";
import { V045_SYSTEM_REMOTE_PASSKEYS_MIGRATION } from "./v045-system-remote-passkeys.js";
import { V046_SYSTEM_REMOTE_DEVICE_PLATFORMS_MIGRATION } from "./v046-system-remote-device-platforms.js";
import { V047_AGENT_LOOP_CLOSEOUT_MIGRATION } from "./v047-agent-loop-closeout.js";
import { V048_OBSERVABILITY_SLO_ALERT_DESTINATIONS_MIGRATION } from "./v048-observability-slo-alert-destinations.js";
import { V049_ACCEPTANCE_RETRY_ADVANCED_MIGRATION } from "./v049-acceptance-retry-advanced.js";
import { V050_AGENT_LOOP_EXPERT_AUTONOMY_MIGRATION } from "./v050-agent-loop-expert-autonomy.js";
import { V051_UIX_COMMUNICATION_PERSONA_MIGRATION } from "./v051-uix-communication-persona.js";
import { V052_RETIRED_FEATURE_RESERVED_D_MIGRATION } from "./v052-retired-feature-reserved-d.js";
import { V053_RETIRED_FEATURE_RESERVED_E_MIGRATION } from "./v053-retired-feature-reserved-e.js";
import { V054_RETIRED_FEATURE_RESERVED_F_MIGRATION } from "./v054-retired-feature-reserved-f.js";
import { V055_RETIRED_FEATURE_RESERVED_G_MIGRATION } from "./v055-retired-feature-reserved-g.js";
import { V056_INCENTIVE_ALIGNMENT_FOUNDATION_MIGRATION } from "./v056-incentive-alignment-foundation.js";
import { V057_AGENT_AUTOMATION_SESSION_TARGETS_MIGRATION } from "./v057-agent-automation-session-targets.js";
import { V058_AGENT_RUN_CONTEXT_PROFILE_MIGRATION } from "./v058-agent-run-context-profile.js";
import { V059_RULES_AUDIT_CANONICALIZATION_MIGRATION } from "./v059-rules-audit-canonicalization.js";
import { V060_UIX_ONBOARDING_SESSIONS_MIGRATION } from "./v060-uix-onboarding-sessions.js";
import { V061_WORLD_MODEL_READINESS_MIGRATION } from "./v061-world-model-readiness.js";
import { V062_UIX_GUIDED_CONTEXTS_MIGRATION } from "./v062-uix-guided-contexts.js";
import { V063_AUTH_PROFILES_MIGRATION } from "./v063-auth-profiles.js";
import { V064_SUBAGENT_FORK_MODE_MIGRATION } from "./v064-subagent-fork-mode.js";
import { V065_AGENT_RUN_CHECKPOINT_MANIFEST_MIGRATION } from "./v065-agent-run-checkpoint-manifest.js";
import { V066_AGENT_RUN_METADATA_MIGRATION } from "./v066-agent-run-metadata.js";
import { V067_CAPABILITY_GRANTS_MIGRATION } from "./v067-capability-grants.js";
import { V068_AUTONOMOUS_ENGINE_PERSISTENCE_MIGRATION } from "./v068-autonomous-engine-persistence.js";
import { V069_AUTONOMY_UPGRADE_METADATA_MIGRATION } from "./v069-autonomy-upgrade-metadata.js";
import { V070_AUTONOMY_SUBJECT_UPGRADE_STATE_MIGRATION } from "./v070-autonomy-subject-upgrade-state.js";
import { V071_AUTONOMOUS_STEP_VERIFICATION_PROVENANCE_MIGRATION } from "./v071-autonomous-step-verification-provenance.js";
import { V072_AUTH_ACCESS_TOKEN_REGISTRY_MIGRATION } from "./v072-auth-access-token-registry.js";
import { V073_OBSERVABILITY_AUDIT_TRAIL_PERSISTENCE_MIGRATION } from "./v073-observability-audit-trail-persistence.js";
import { V074_CONTROLLED_AUTONOMY_CLOSED_LOOPS_MIGRATION } from "./v074-controlled-autonomy-closed-loops.js";
import { V075_REFLEX_LOOP_ONBOARDING_MIGRATION } from "./v075-reflex-loop-onboarding.js";
import { V076_PROVIDER_OAUTH_USER_SCOPE_MIGRATION } from "./v076-provider-oauth-user-scope.js";
import { V077_AGENT_CONTEXT_REPLAY_MIGRATION } from "./v077-agent-context-replay.js";
import { V078_MEMORY_TYPE_CONFIDENCE_MIGRATION } from "./v078-memory-type-confidence.js";
import { V079_PACKAGING_PERSISTENCE_MIGRATION } from "./v079-packaging-persistence.js";
import { V080_MULTI_TENANT_SECURITY_PERSISTENCE_MIGRATION } from "./v080-multi-tenant-security-persistence.js";
import { V081_TASK_WORKFLOW_POLICY_MIGRATION } from "./v081-task-workflow-policy.js";
import { V082_TASK_WORKFLOW_LANES_MIGRATION } from "./v082-task-workflow-lanes.js";
import { V083_TASK_WORKFLOW_LANE_CLI_ROLE_MIGRATION } from "./v083-task-workflow-lane-cli-role.js";
import { V084_TASK_WORKFLOW_CLI_HANDOFFS_MIGRATION } from "./v084-task-workflow-cli-handoffs.js";
import { V085_TASK_WORKFLOW_CHANNEL_COMMANDS_MIGRATION } from "./v085-task-workflow-channel-commands.js";
import { V086_WORKFLOW_EVIDENCE_FAIL_CLOSED_MIGRATION } from "./v086-workflow-evidence-fail-closed.js";
import { V087_ROLLBACK_MATRIX_CLOSEOUT_RECEIPT_MIGRATION } from "./v087-rollback-matrix-closeout-receipt.js";
import { V088_AUTO_FIX_ROLLBACK_RECEIPT_MIGRATION } from "./v088-auto-fix-rollback-receipt.js";
import { V089_WORKFLOW_COMPLETION_VERIFICATION_MIGRATION } from "./v089-workflow-completion-verification.js";
import { V090_REFLEX_LEARNED_FACT_CANDIDATES_MIGRATION } from "./v090-reflex-learned-fact-candidates.js";
import { V091_PREFERENCE_FACT_METADATA_MIGRATION } from "./v091-preference-fact-metadata.js";
import { V092_REFLEX_SECURE_FACT_CANDIDATES_MIGRATION } from "./v092-reflex-secure-fact-candidates.js";
import { V093_WORKFLOW_BUILDER_DRAFT_REHOME_MIGRATION } from "./v093-workflow-builder-draft-rehome.js";
import { V094_WORKFLOW_BUILDER_ANCILLARY_REHOME_MIGRATION } from "./v094-workflow-builder-ancillary-rehome.js";
import { V095_SKILL_RUNS_REHOME_MIGRATION } from "./v095-skill-runs-rehome.js";
import { V096_SKILL_GENERATOR_REHOME_MIGRATION } from "./v096-skill-generator-rehome.js";
import { V097_WORKFLOW_GENERATOR_REHOME_MIGRATION } from "./v097-workflow-generator-rehome.js";
import { V098_TEMPLATE_HARNESS_REHOME_MIGRATION } from "./v098-template-harness-rehome.js";
import { V099_AGENT_RUN_ORGANIC_PROVENANCE_MIGRATION } from "./v099-agent-run-organic-provenance.js";
import { V100_OPERATION_JOURNAL_MIGRATION } from "./v100-operation-journal.js";
import { V101_TELEGRAM_INBOX_MIGRATION } from "./v101-telegram-inbox.js";
import { V102_PROVIDER_CALL_RECEIPT_MIGRATION } from "./v102-provider-call-receipt.js";
import { V103_SETUP_BOOTSTRAP_DEVICE_CLAIM_MIGRATION } from "./v103-setup-bootstrap-device-claim.js";
import { V104_SETUP_BOOTSTRAP_MIGRATION_STATE_MIGRATION } from "./v104-setup-bootstrap-migration-state.js";
import { V105_RETENTION_SETTINGS_MIGRATION } from "./v105-retention-settings.js";
import { V106_REALTIME_EVENTS_OWNER_MIGRATION } from "./v106-realtime-events-owner.js";
import { V107_SETUP_BOOTSTRAP_LOGIN_CHALLENGE_MIGRATION } from "./v107-setup-bootstrap-login-challenge.js";

/**
 * Ordered migration list, always ascending by version.
 */
export const FRIDAY_SQLITE_MIGRATIONS: readonly FridaySqliteMigration[] = [
  V001_INITIAL_MIGRATION,
  V002_PHASE8_API_FOUNDATION_MIGRATION,
  V003_PROVIDER_USAGE_COST_ROUTING_MIGRATION,
  V004_MEMORY_CORE_MIGRATION,
  V005_SESSION_FOUNDATION_MIGRATION,
  V006_SESSION_MEMORY_EXTRACTION_MIGRATION,
  V007_SESSION_FORKS_MIGRATION,
  V008_PLUGIN_SYSTEM_FOUNDATION_MIGRATION,
  V009_WORKFLOW_ENGINE_TRIGGERS_APPROVALS_MIGRATION,
  V010_PROVIDER_OAUTH_CREDENTIALS_MIGRATION,
  V011_ACCESS_TOKEN_REVOCATION_MIGRATION,
  V012_AGENT_RUNTIME_MIGRATION,
  V013_SUBAGENT_RUNS_MIGRATION,
  V014_SETUP_WIZARD_MIGRATION,
  V015_XHS_SESSIONS_MIGRATION,
  V016_XHS_COOKIE_ENCRYPTION_MIGRATION,
  V017_AGENT_RUN_PLAN_REVIEW_MIGRATION,
  V018_AGENT_RUN_ACTUAL_EXECUTION_MIGRATION,
  V019_AGENT_RUN_EVENTS_MIGRATION,
  V020_AGENT_RUN_CONSTRAINTS_MIGRATION,
  V021_AGENT_RUN_RESPONSE_TEXT_SUMMARY_MIGRATION,
  V022_AGENT_RUN_ARTIFACT_DIR_MIGRATION,
  V023_MEMORY_FILE_SYNC_MIGRATION,
  V024_UNIFIED_JOB_SCHEDULER_MIGRATION,
  V025_MEMORY_FILE_SYNC_TRIGGER_FIXES_MIGRATION,
  V026_MEMORY_FILE_SYNC_EXTERNAL_MIGRATION,
  V027_JOB_SCHEDULER_MULTI_SCHEDULE_MIGRATION,
  V028_SUBAGENT_LIFECYCLE_SESSION_SEND_POLICY_MIGRATION,
  V029_HEARTBEAT_RUNNER_STATE_MIGRATION,
  V030_AGENT_AUTOMATION_SCHEDULE_LINK_MIGRATION,
  V031_RULES_PERSISTENCE_MIGRATION,
  V032_PLAYBOOK_PERSISTENCE_MIGRATION,
  V033_WORKFLOW_RUN_EVIDENCE_PERSISTENCE_MIGRATION,
  V034_RULES_SCHEMA_BRIDGE_MIGRATION,
  V035_AUTH_TOKEN_INDEXES_MIGRATION,
  V036_WORKFLOW_INDEXES_MIGRATION,
  V037_FK_AND_PLAYBOOK_INDEX_MIGRATION,
  V038_RETIRED_FEATURE_RESERVED_A_MIGRATION,
  V039_RETIRED_FEATURE_RESERVED_B_MIGRATION,
  V040_SETUP_STATE_REVISION_MIGRATION,
  V041_CHANNEL_AGENT_BINDINGS_MIGRATION,
  V042_RETIRED_FEATURE_RESERVED_C_MIGRATION,
  V043_SYSTEM_AGENT_OS_LAYER_MIGRATION,
  V044_SYSTEM_REMOTE_SESSIONS_MIGRATION,
  V045_SYSTEM_REMOTE_PASSKEYS_MIGRATION,
  V046_SYSTEM_REMOTE_DEVICE_PLATFORMS_MIGRATION,
  V047_AGENT_LOOP_CLOSEOUT_MIGRATION,
  V048_OBSERVABILITY_SLO_ALERT_DESTINATIONS_MIGRATION,
  V049_ACCEPTANCE_RETRY_ADVANCED_MIGRATION,
  V050_AGENT_LOOP_EXPERT_AUTONOMY_MIGRATION,
  V051_UIX_COMMUNICATION_PERSONA_MIGRATION,
  V052_RETIRED_FEATURE_RESERVED_D_MIGRATION,
  V053_RETIRED_FEATURE_RESERVED_E_MIGRATION,
  V054_RETIRED_FEATURE_RESERVED_F_MIGRATION,
  V055_RETIRED_FEATURE_RESERVED_G_MIGRATION,
  V056_INCENTIVE_ALIGNMENT_FOUNDATION_MIGRATION,
  V057_AGENT_AUTOMATION_SESSION_TARGETS_MIGRATION,
  V058_AGENT_RUN_CONTEXT_PROFILE_MIGRATION,
  V059_RULES_AUDIT_CANONICALIZATION_MIGRATION,
  V060_UIX_ONBOARDING_SESSIONS_MIGRATION,
  V061_WORLD_MODEL_READINESS_MIGRATION,
  V062_UIX_GUIDED_CONTEXTS_MIGRATION,
  V063_AUTH_PROFILES_MIGRATION,
  V064_SUBAGENT_FORK_MODE_MIGRATION,
  V065_AGENT_RUN_CHECKPOINT_MANIFEST_MIGRATION,
  V066_AGENT_RUN_METADATA_MIGRATION,
  V067_CAPABILITY_GRANTS_MIGRATION,
  V068_AUTONOMOUS_ENGINE_PERSISTENCE_MIGRATION,
  V069_AUTONOMY_UPGRADE_METADATA_MIGRATION,
  V070_AUTONOMY_SUBJECT_UPGRADE_STATE_MIGRATION,
  V071_AUTONOMOUS_STEP_VERIFICATION_PROVENANCE_MIGRATION,
  V072_AUTH_ACCESS_TOKEN_REGISTRY_MIGRATION,
  V073_OBSERVABILITY_AUDIT_TRAIL_PERSISTENCE_MIGRATION,
  V074_CONTROLLED_AUTONOMY_CLOSED_LOOPS_MIGRATION,
  V075_REFLEX_LOOP_ONBOARDING_MIGRATION,
  V076_PROVIDER_OAUTH_USER_SCOPE_MIGRATION,
  V077_AGENT_CONTEXT_REPLAY_MIGRATION,
  V078_MEMORY_TYPE_CONFIDENCE_MIGRATION,
  V079_PACKAGING_PERSISTENCE_MIGRATION,
  V080_MULTI_TENANT_SECURITY_PERSISTENCE_MIGRATION,
  V081_TASK_WORKFLOW_POLICY_MIGRATION,
  V082_TASK_WORKFLOW_LANES_MIGRATION,
  V083_TASK_WORKFLOW_LANE_CLI_ROLE_MIGRATION,
  V084_TASK_WORKFLOW_CLI_HANDOFFS_MIGRATION,
  V085_TASK_WORKFLOW_CHANNEL_COMMANDS_MIGRATION,
  V086_WORKFLOW_EVIDENCE_FAIL_CLOSED_MIGRATION,
  V087_ROLLBACK_MATRIX_CLOSEOUT_RECEIPT_MIGRATION,
  V088_AUTO_FIX_ROLLBACK_RECEIPT_MIGRATION,
  V089_WORKFLOW_COMPLETION_VERIFICATION_MIGRATION,
  V090_REFLEX_LEARNED_FACT_CANDIDATES_MIGRATION,
  V091_PREFERENCE_FACT_METADATA_MIGRATION,
  V092_REFLEX_SECURE_FACT_CANDIDATES_MIGRATION,
  V093_WORKFLOW_BUILDER_DRAFT_REHOME_MIGRATION,
  V094_WORKFLOW_BUILDER_ANCILLARY_REHOME_MIGRATION,
  V095_SKILL_RUNS_REHOME_MIGRATION,
  V096_SKILL_GENERATOR_REHOME_MIGRATION,
  V097_WORKFLOW_GENERATOR_REHOME_MIGRATION,
  V098_TEMPLATE_HARNESS_REHOME_MIGRATION,
  V099_AGENT_RUN_ORGANIC_PROVENANCE_MIGRATION,
  V100_OPERATION_JOURNAL_MIGRATION,
  V101_TELEGRAM_INBOX_MIGRATION,
  V102_PROVIDER_CALL_RECEIPT_MIGRATION,
  V103_SETUP_BOOTSTRAP_DEVICE_CLAIM_MIGRATION,
  V104_SETUP_BOOTSTRAP_MIGRATION_STATE_MIGRATION,
  V105_RETENTION_SETTINGS_MIGRATION,
  V106_REALTIME_EVENTS_OWNER_MIGRATION,
  V107_SETUP_BOOTSTRAP_LOGIN_CHALLENGE_MIGRATION,
];

export { V003_PROVIDER_USAGE_COST_ROUTING_MIGRATION };
export { V004_MEMORY_CORE_MIGRATION };
export { V005_SESSION_FOUNDATION_MIGRATION };
export { V006_SESSION_MEMORY_EXTRACTION_MIGRATION };
export { V007_SESSION_FORKS_MIGRATION };
export { V008_PLUGIN_SYSTEM_FOUNDATION_MIGRATION };
export { V009_WORKFLOW_ENGINE_TRIGGERS_APPROVALS_MIGRATION };
export { V010_PROVIDER_OAUTH_CREDENTIALS_MIGRATION };
export { V011_ACCESS_TOKEN_REVOCATION_MIGRATION };
export { V012_AGENT_RUNTIME_MIGRATION };
export { V013_SUBAGENT_RUNS_MIGRATION };
export { V014_SETUP_WIZARD_MIGRATION };
export { V015_XHS_SESSIONS_MIGRATION };
export { V016_XHS_COOKIE_ENCRYPTION_MIGRATION };
export { V017_AGENT_RUN_PLAN_REVIEW_MIGRATION };
export { V018_AGENT_RUN_ACTUAL_EXECUTION_MIGRATION };
export { V019_AGENT_RUN_EVENTS_MIGRATION };
export { V020_AGENT_RUN_CONSTRAINTS_MIGRATION };
export { V021_AGENT_RUN_RESPONSE_TEXT_SUMMARY_MIGRATION };
export { V022_AGENT_RUN_ARTIFACT_DIR_MIGRATION };
export { V023_MEMORY_FILE_SYNC_MIGRATION };
export { V024_UNIFIED_JOB_SCHEDULER_MIGRATION };
export { V025_MEMORY_FILE_SYNC_TRIGGER_FIXES_MIGRATION };
export { V026_MEMORY_FILE_SYNC_EXTERNAL_MIGRATION };
export { V027_JOB_SCHEDULER_MULTI_SCHEDULE_MIGRATION };
export { V028_SUBAGENT_LIFECYCLE_SESSION_SEND_POLICY_MIGRATION };
export { V029_HEARTBEAT_RUNNER_STATE_MIGRATION };
export { V030_AGENT_AUTOMATION_SCHEDULE_LINK_MIGRATION };
export { V031_RULES_PERSISTENCE_MIGRATION };
export { V032_PLAYBOOK_PERSISTENCE_MIGRATION };
export { V033_WORKFLOW_RUN_EVIDENCE_PERSISTENCE_MIGRATION };
export { V034_RULES_SCHEMA_BRIDGE_MIGRATION };
export { V035_AUTH_TOKEN_INDEXES_MIGRATION };
export { V036_WORKFLOW_INDEXES_MIGRATION };
export { V037_FK_AND_PLAYBOOK_INDEX_MIGRATION };
export { V038_RETIRED_FEATURE_RESERVED_A_MIGRATION };
export { V039_RETIRED_FEATURE_RESERVED_B_MIGRATION };
export { V040_SETUP_STATE_REVISION_MIGRATION };
export { V041_CHANNEL_AGENT_BINDINGS_MIGRATION };
export { V042_RETIRED_FEATURE_RESERVED_C_MIGRATION };
export { V043_SYSTEM_AGENT_OS_LAYER_MIGRATION };
export { V044_SYSTEM_REMOTE_SESSIONS_MIGRATION };
export { V045_SYSTEM_REMOTE_PASSKEYS_MIGRATION };
export { V046_SYSTEM_REMOTE_DEVICE_PLATFORMS_MIGRATION };
export { V047_AGENT_LOOP_CLOSEOUT_MIGRATION };
export { V048_OBSERVABILITY_SLO_ALERT_DESTINATIONS_MIGRATION };
export { V049_ACCEPTANCE_RETRY_ADVANCED_MIGRATION };
export { V050_AGENT_LOOP_EXPERT_AUTONOMY_MIGRATION };
export { V051_UIX_COMMUNICATION_PERSONA_MIGRATION };
export { V052_RETIRED_FEATURE_RESERVED_D_MIGRATION };
export { V053_RETIRED_FEATURE_RESERVED_E_MIGRATION };
export { V054_RETIRED_FEATURE_RESERVED_F_MIGRATION };
export { V055_RETIRED_FEATURE_RESERVED_G_MIGRATION };
export { V056_INCENTIVE_ALIGNMENT_FOUNDATION_MIGRATION };
export { V057_AGENT_AUTOMATION_SESSION_TARGETS_MIGRATION };
export { V058_AGENT_RUN_CONTEXT_PROFILE_MIGRATION };
export { V059_RULES_AUDIT_CANONICALIZATION_MIGRATION };
export { V060_UIX_ONBOARDING_SESSIONS_MIGRATION };
export { V061_WORLD_MODEL_READINESS_MIGRATION };
export { V062_UIX_GUIDED_CONTEXTS_MIGRATION };
export { V063_AUTH_PROFILES_MIGRATION };
export { V064_SUBAGENT_FORK_MODE_MIGRATION };
export { V065_AGENT_RUN_CHECKPOINT_MANIFEST_MIGRATION };
export { V066_AGENT_RUN_METADATA_MIGRATION };
export { V067_CAPABILITY_GRANTS_MIGRATION };
export { V068_AUTONOMOUS_ENGINE_PERSISTENCE_MIGRATION };
export { V069_AUTONOMY_UPGRADE_METADATA_MIGRATION };
export { V070_AUTONOMY_SUBJECT_UPGRADE_STATE_MIGRATION };
export { V071_AUTONOMOUS_STEP_VERIFICATION_PROVENANCE_MIGRATION };
export { V072_AUTH_ACCESS_TOKEN_REGISTRY_MIGRATION };
export { V073_OBSERVABILITY_AUDIT_TRAIL_PERSISTENCE_MIGRATION };
export { V074_CONTROLLED_AUTONOMY_CLOSED_LOOPS_MIGRATION };
export { V075_REFLEX_LOOP_ONBOARDING_MIGRATION };
export { V076_PROVIDER_OAUTH_USER_SCOPE_MIGRATION };
export { V077_AGENT_CONTEXT_REPLAY_MIGRATION };
export { V078_MEMORY_TYPE_CONFIDENCE_MIGRATION };
export { V079_PACKAGING_PERSISTENCE_MIGRATION };
export { V080_MULTI_TENANT_SECURITY_PERSISTENCE_MIGRATION };
export { V081_TASK_WORKFLOW_POLICY_MIGRATION };
export { V082_TASK_WORKFLOW_LANES_MIGRATION };
export { V083_TASK_WORKFLOW_LANE_CLI_ROLE_MIGRATION };
export { V084_TASK_WORKFLOW_CLI_HANDOFFS_MIGRATION };
export { V085_TASK_WORKFLOW_CHANNEL_COMMANDS_MIGRATION };
export { V086_WORKFLOW_EVIDENCE_FAIL_CLOSED_MIGRATION };
export { V087_ROLLBACK_MATRIX_CLOSEOUT_RECEIPT_MIGRATION };
export { V088_AUTO_FIX_ROLLBACK_RECEIPT_MIGRATION };
export { V090_REFLEX_LEARNED_FACT_CANDIDATES_MIGRATION };
export { V091_PREFERENCE_FACT_METADATA_MIGRATION };
export { V092_REFLEX_SECURE_FACT_CANDIDATES_MIGRATION };
export { V094_WORKFLOW_BUILDER_ANCILLARY_REHOME_MIGRATION };
export { V095_SKILL_RUNS_REHOME_MIGRATION };
export { V096_SKILL_GENERATOR_REHOME_MIGRATION };
export { V097_WORKFLOW_GENERATOR_REHOME_MIGRATION };
export { V098_TEMPLATE_HARNESS_REHOME_MIGRATION };
export { V099_AGENT_RUN_ORGANIC_PROVENANCE_MIGRATION };
export { V100_OPERATION_JOURNAL_MIGRATION };
export { V101_TELEGRAM_INBOX_MIGRATION };
export { V102_PROVIDER_CALL_RECEIPT_MIGRATION };
