import type { FridaySqliteMigration } from "./friday-migration.types.js";
import { V001_INITIAL_MIGRATION } from "./v001-initial.js";
import { V002_PHASE8_API_FOUNDATION_MIGRATION } from "./v002-phase8-api-foundation.js";
import { V003_PROVIDER_USAGE_COST_ROUTING_MIGRATION } from "./v003-provider-usage-cost-routing.js";
import { V004_MEMORY_CORE_MIGRATION } from "./v004-memory-core.js";
import { V005_SESSION_FOUNDATION_MIGRATION } from "./v005-session-foundation.js";
import { V006_SESSION_MEMORY_EXTRACTION_MIGRATION } from "./v006-session-memory-extraction.js";
import { V007_SESSION_FORKS_MIGRATION } from "./v007-session-forks.js";
import { V008_PLUGIN_SYSTEM_FOUNDATION_MIGRATION } from "./v008-plugin-system-foundation.js";
import { V009_WORKFLOW_ENGINE_TRIGGERS_APPROVALS_MIGRATION } from "./v009-workflow-engine-triggers-approvals.js";
import { V010_PROVIDER_OAUTH_CREDENTIALS_MIGRATION } from "./v010-provider-oauth-credentials.js";
import { V011_ACCESS_TOKEN_REVOCATION_MIGRATION } from "./v011-access-token-revocation.js";
import { V012_AGENT_RUNTIME_MIGRATION } from "./v012-agent-runtime.js";
import { V013_SUBAGENT_RUNS_MIGRATION } from "./v013-subagent-runs.js";
import { V014_SETUP_WIZARD_MIGRATION } from "./v014-setup-wizard.js";
import { V015_XHS_SESSIONS_MIGRATION } from "./v015-xhs-sessions.js";
import { V016_XHS_COOKIE_ENCRYPTION_MIGRATION } from "./v016-xhs-cookie-encryption.js";
import { V017_AGENT_RUN_PLAN_REVIEW_MIGRATION } from "./v017-agent-run-plan-review.js";
import { V018_AGENT_RUN_ACTUAL_EXECUTION_MIGRATION } from "./v018-agent-run-actual-execution.js";
import { V019_AGENT_RUN_EVENTS_MIGRATION } from "./v019-agent-run-events.js";
import { V020_AGENT_RUN_CONSTRAINTS_MIGRATION } from "./v020-agent-run-constraints.js";
import { V021_AGENT_RUN_RESPONSE_TEXT_SUMMARY_MIGRATION } from "./v021-agent-run-response-text-summary.js";
import { V022_AGENT_RUN_ARTIFACT_DIR_MIGRATION } from "./v022-agent-run-artifact-dir.js";
import { V023_MEMORY_FILE_SYNC_MIGRATION } from "./v023-memory-file-sync.js";
import { V024_UNIFIED_JOB_SCHEDULER_MIGRATION } from "./v024-unified-job-scheduler.js";
import { V025_MEMORY_FILE_SYNC_TRIGGER_FIXES_MIGRATION } from "./v025-memory-file-sync-trigger-fixes.js";
import { V026_MEMORY_FILE_SYNC_EXTERNAL_MIGRATION } from "./v026-memory-file-sync-external.js";
import { V027_JOB_SCHEDULER_MULTI_SCHEDULE_MIGRATION } from "./v027-job-scheduler-multi-schedule.js";
import { V028_SUBAGENT_LIFECYCLE_SESSION_SEND_POLICY_MIGRATION } from "./v028-subagent-lifecycle-session-send-policy.js";
import { V029_HEARTBEAT_RUNNER_STATE_MIGRATION } from "./v029-heartbeat-runner-state.js";
import { V030_AGENT_AUTOMATION_SCHEDULE_LINK_MIGRATION } from "./v030-agent-automation-schedule-link.js";
import { V031_RULES_PERSISTENCE_MIGRATION } from "./v031-rules-persistence.js";
import { V032_PLAYBOOK_PERSISTENCE_MIGRATION } from "./v032-playbook-persistence.js";
import { V033_WORKFLOW_RUN_EVIDENCE_PERSISTENCE_MIGRATION } from "./v033-workflow-run-evidence-persistence.js";
import { V034_RULES_SCHEMA_BRIDGE_MIGRATION } from "./v034-rules-schema-bridge.js";
import { V035_AUTH_TOKEN_INDEXES_MIGRATION } from "./v035-auth-token-indexes.js";
import { V036_WORKFLOW_INDEXES_MIGRATION } from "./v036-workflow-indexes.js";
import { V037_FK_AND_PLAYBOOK_INDEX_MIGRATION } from "./v037-fk-and-playbook-index.js";
import { V038_MARKETPLACE_COMMERCE_MVP_MIGRATION } from "./v038-marketplace-commerce-mvp.js";
import { V039_MARKETPLACE_INSTALLATIONS_MVP_MIGRATION } from "./v039-marketplace-installations-mvp.js";
import { V040_SETUP_STATE_REVISION_MIGRATION } from "./v040-setup-state-revision.js";
import { V041_CHANNEL_AGENT_BINDINGS_MIGRATION } from "./v041-channel-agent-bindings.js";
import { V042_MARKETPLACE_PAYOUT_BILLING_MVP_MIGRATION } from "./v042-marketplace-payout-billing-mvp.js";
import { V043_SYSTEM_AGENT_OS_LAYER_MIGRATION } from "./v043-system-agent-os-layer.js";
import { V044_SYSTEM_REMOTE_SESSIONS_MIGRATION } from "./v044-system-remote-sessions.js";
import { V045_SYSTEM_REMOTE_PASSKEYS_MIGRATION } from "./v045-system-remote-passkeys.js";
import { V046_SYSTEM_REMOTE_DEVICE_PLATFORMS_MIGRATION } from "./v046-system-remote-device-platforms.js";
import { V047_AGENT_LOOP_CLOSEOUT_MIGRATION } from "./v047-agent-loop-closeout.js";
import { V048_OBSERVABILITY_SLO_ALERT_DESTINATIONS_MIGRATION } from "./v048-observability-slo-alert-destinations.js";
import { V049_ACCEPTANCE_RETRY_ADVANCED_MIGRATION } from "./v049-acceptance-retry-advanced.js";
import { V050_AGENT_LOOP_EXPERT_AUTONOMY_MIGRATION } from "./v050-agent-loop-expert-autonomy.js";
import { V051_UIX_COMMUNICATION_PERSONA_MIGRATION } from "./v051-uix-communication-persona.js";
import { V052_MARKETPLACE_SAFE_ASSETS_MIGRATION } from "./v052-marketplace-safe-assets.js";
import { V053_MARKETPLACE_CREATOR_SUPPORT_MIGRATION } from "./v053-marketplace-creator-support.js";
import { V054_MARKETPLACE_REQUEST_BOARD_MIGRATION } from "./v054-marketplace-request-board.js";
import { V055_MARKETPLACE_ACTOR_ISOLATION_MIGRATION } from "./v055-marketplace-actor-isolation.js";
import { V056_INCENTIVE_ALIGNMENT_FOUNDATION_MIGRATION } from "./v056-incentive-alignment-foundation.js";
import { V057_AGENT_RUN_CONTEXT_PROFILE_MIGRATION } from "./v057-agent-run-context-profile.js";

/**
 * Ordered migration list, always ascending by version.
 */
export const FRIDAY_SQLITE_MIGRATIONS: readonly FridaySqliteMigration[] = [
  V001_INITIAL_MIGRATION,
  V002_PHASE8_API_FOUNDATION_MIGRATION,
  V003_PROVIDER_USAGE_COST_ROUTING_MIGRATION,
  V004_MEMORY_CORE_MIGRATION,
  V005_SESSION_FOUNDATION_MIGRATION,
  V006_SESSION_MEMORY_EXTRACTION_MIGRATION,
  V007_SESSION_FORKS_MIGRATION,
  V008_PLUGIN_SYSTEM_FOUNDATION_MIGRATION,
  V009_WORKFLOW_ENGINE_TRIGGERS_APPROVALS_MIGRATION,
  V010_PROVIDER_OAUTH_CREDENTIALS_MIGRATION,
  V011_ACCESS_TOKEN_REVOCATION_MIGRATION,
  V012_AGENT_RUNTIME_MIGRATION,
  V013_SUBAGENT_RUNS_MIGRATION,
  V014_SETUP_WIZARD_MIGRATION,
  V015_XHS_SESSIONS_MIGRATION,
  V016_XHS_COOKIE_ENCRYPTION_MIGRATION,
  V017_AGENT_RUN_PLAN_REVIEW_MIGRATION,
  V018_AGENT_RUN_ACTUAL_EXECUTION_MIGRATION,
  V019_AGENT_RUN_EVENTS_MIGRATION,
  V020_AGENT_RUN_CONSTRAINTS_MIGRATION,
  V021_AGENT_RUN_RESPONSE_TEXT_SUMMARY_MIGRATION,
  V022_AGENT_RUN_ARTIFACT_DIR_MIGRATION,
  V023_MEMORY_FILE_SYNC_MIGRATION,
  V024_UNIFIED_JOB_SCHEDULER_MIGRATION,
  V025_MEMORY_FILE_SYNC_TRIGGER_FIXES_MIGRATION,
  V026_MEMORY_FILE_SYNC_EXTERNAL_MIGRATION,
  V027_JOB_SCHEDULER_MULTI_SCHEDULE_MIGRATION,
  V028_SUBAGENT_LIFECYCLE_SESSION_SEND_POLICY_MIGRATION,
  V029_HEARTBEAT_RUNNER_STATE_MIGRATION,
  V030_AGENT_AUTOMATION_SCHEDULE_LINK_MIGRATION,
  V031_RULES_PERSISTENCE_MIGRATION,
  V032_PLAYBOOK_PERSISTENCE_MIGRATION,
  V033_WORKFLOW_RUN_EVIDENCE_PERSISTENCE_MIGRATION,
  V034_RULES_SCHEMA_BRIDGE_MIGRATION,
  V035_AUTH_TOKEN_INDEXES_MIGRATION,
  V036_WORKFLOW_INDEXES_MIGRATION,
  V037_FK_AND_PLAYBOOK_INDEX_MIGRATION,
  V038_MARKETPLACE_COMMERCE_MVP_MIGRATION,
  V039_MARKETPLACE_INSTALLATIONS_MVP_MIGRATION,
  V040_SETUP_STATE_REVISION_MIGRATION,
  V041_CHANNEL_AGENT_BINDINGS_MIGRATION,
  V042_MARKETPLACE_PAYOUT_BILLING_MVP_MIGRATION,
  V043_SYSTEM_AGENT_OS_LAYER_MIGRATION,
  V044_SYSTEM_REMOTE_SESSIONS_MIGRATION,
  V045_SYSTEM_REMOTE_PASSKEYS_MIGRATION,
  V046_SYSTEM_REMOTE_DEVICE_PLATFORMS_MIGRATION,
  V047_AGENT_LOOP_CLOSEOUT_MIGRATION,
  V048_OBSERVABILITY_SLO_ALERT_DESTINATIONS_MIGRATION,
  V049_ACCEPTANCE_RETRY_ADVANCED_MIGRATION,
  V050_AGENT_LOOP_EXPERT_AUTONOMY_MIGRATION,
  V051_UIX_COMMUNICATION_PERSONA_MIGRATION,
  V052_MARKETPLACE_SAFE_ASSETS_MIGRATION,
  V053_MARKETPLACE_CREATOR_SUPPORT_MIGRATION,
  V054_MARKETPLACE_REQUEST_BOARD_MIGRATION,
  V055_MARKETPLACE_ACTOR_ISOLATION_MIGRATION,
  V056_INCENTIVE_ALIGNMENT_FOUNDATION_MIGRATION,
  V057_AGENT_RUN_CONTEXT_PROFILE_MIGRATION,
];

export { V003_PROVIDER_USAGE_COST_ROUTING_MIGRATION };
export { V004_MEMORY_CORE_MIGRATION };
export { V005_SESSION_FOUNDATION_MIGRATION };
export { V006_SESSION_MEMORY_EXTRACTION_MIGRATION };
export { V007_SESSION_FORKS_MIGRATION };
export { V008_PLUGIN_SYSTEM_FOUNDATION_MIGRATION };
export { V009_WORKFLOW_ENGINE_TRIGGERS_APPROVALS_MIGRATION };
export { V010_PROVIDER_OAUTH_CREDENTIALS_MIGRATION };
export { V011_ACCESS_TOKEN_REVOCATION_MIGRATION };
export { V012_AGENT_RUNTIME_MIGRATION };
export { V013_SUBAGENT_RUNS_MIGRATION };
export { V014_SETUP_WIZARD_MIGRATION };
export { V015_XHS_SESSIONS_MIGRATION };
export { V016_XHS_COOKIE_ENCRYPTION_MIGRATION };
export { V017_AGENT_RUN_PLAN_REVIEW_MIGRATION };
export { V018_AGENT_RUN_ACTUAL_EXECUTION_MIGRATION };
export { V019_AGENT_RUN_EVENTS_MIGRATION };
export { V020_AGENT_RUN_CONSTRAINTS_MIGRATION };
export { V021_AGENT_RUN_RESPONSE_TEXT_SUMMARY_MIGRATION };
export { V022_AGENT_RUN_ARTIFACT_DIR_MIGRATION };
export { V023_MEMORY_FILE_SYNC_MIGRATION };
export { V024_UNIFIED_JOB_SCHEDULER_MIGRATION };
export { V025_MEMORY_FILE_SYNC_TRIGGER_FIXES_MIGRATION };
export { V026_MEMORY_FILE_SYNC_EXTERNAL_MIGRATION };
export { V027_JOB_SCHEDULER_MULTI_SCHEDULE_MIGRATION };
export { V028_SUBAGENT_LIFECYCLE_SESSION_SEND_POLICY_MIGRATION };
export { V029_HEARTBEAT_RUNNER_STATE_MIGRATION };
export { V030_AGENT_AUTOMATION_SCHEDULE_LINK_MIGRATION };
export { V031_RULES_PERSISTENCE_MIGRATION };
export { V032_PLAYBOOK_PERSISTENCE_MIGRATION };
export { V033_WORKFLOW_RUN_EVIDENCE_PERSISTENCE_MIGRATION };
export { V034_RULES_SCHEMA_BRIDGE_MIGRATION };
export { V035_AUTH_TOKEN_INDEXES_MIGRATION };
export { V036_WORKFLOW_INDEXES_MIGRATION };
export { V037_FK_AND_PLAYBOOK_INDEX_MIGRATION };
export { V038_MARKETPLACE_COMMERCE_MVP_MIGRATION };
export { V039_MARKETPLACE_INSTALLATIONS_MVP_MIGRATION };
export { V040_SETUP_STATE_REVISION_MIGRATION };
export { V041_CHANNEL_AGENT_BINDINGS_MIGRATION };
export { V042_MARKETPLACE_PAYOUT_BILLING_MVP_MIGRATION };
export { V043_SYSTEM_AGENT_OS_LAYER_MIGRATION };
export { V044_SYSTEM_REMOTE_SESSIONS_MIGRATION };
export { V045_SYSTEM_REMOTE_PASSKEYS_MIGRATION };
export { V046_SYSTEM_REMOTE_DEVICE_PLATFORMS_MIGRATION };
export { V047_AGENT_LOOP_CLOSEOUT_MIGRATION };
export { V048_OBSERVABILITY_SLO_ALERT_DESTINATIONS_MIGRATION };
export { V049_ACCEPTANCE_RETRY_ADVANCED_MIGRATION };
export { V050_AGENT_LOOP_EXPERT_AUTONOMY_MIGRATION };
export { V051_UIX_COMMUNICATION_PERSONA_MIGRATION };
export { V052_MARKETPLACE_SAFE_ASSETS_MIGRATION };
export { V053_MARKETPLACE_CREATOR_SUPPORT_MIGRATION };
export { V054_MARKETPLACE_REQUEST_BOARD_MIGRATION };
export { V055_MARKETPLACE_ACTOR_ISOLATION_MIGRATION };
export { V056_INCENTIVE_ALIGNMENT_FOUNDATION_MIGRATION };
export { V057_AGENT_RUN_CONTEXT_PROFILE_MIGRATION };
